### ISSUE TITLE
Windows are opaque

### ISSUE THREAD

**Issue by flyingfisch** [Juanvvc/c172p-detailed#114]
Just got the latest and the windows are opaque. Anyone else having this issue?

Ubuntu 14.04
FG 3.4

**Comment by gilbertohasnofb** [comment]
Our plane only works on FG 3.5 since we use many new features that are not present in FG 3.4, such as window reflections and other glass and shadow effects. This is the reason you see opaque windows. To solve this, you have two options: either install FG 3.5 from git or wait until the next stable release (FG 3.6).

**Comment by flyingfisch** [comment]
Can I disable the effects in the XML?

**Comment by gilbertohasnofb** [comment]
I am not sure how to do that. Let's ask @wlbragg who is responsible for these effects.

**Comment by flyingfisch** [comment]
Ok cool.

**Comment by Juanvvc** [comment]
Yes, two options:

(1) Preferred: try the branch: internal-shadow-control instead of master: https://github.com/Juanvvc/c172p-detailed/tree/internal-shadow-control Unfortunately, one user reported in the forum this branch does not work in FG3.2 :(
(2) get master again, open the XML and replace all "Models/Effects/interior/c172p-interior-glass-reflection-front.eff" and "Models/Effects/interior/c172p-interior-glass-reflection-side.eff" and "Models/Effects/interior/c172p-interior-glass-shadow.eff" with the old effect "Effects/model-transparent". Also, remove the XML code that activates the effect "Models/Effects/c172p-interior.eff" and shadows.

**Comment by flyingfisch** [comment]
Thanks, i tried option one and it was a bit glitchy. I'll try option two and let you know how it goes.

I really appreciate the quick feedback, and I have a few FOSS projects of my own, so i totally get your second paragraph.

Once again, thanks, and kudos for this project!

**Comment by flyingfisch** [comment]
OK, tried option two, working perfectly. If you want I could try writing a shell script to find and replace the non-backwards compatible code so that you can easily post updates for both versions. Let me know if you think this would be a good idea and I will write it and send in a pull request.

**Comment by flyingfisch** [comment]
K forked. I can't seem to get a `*-set.xml` for each one and have it work... can someone take a look at that?

**Comment by onox** [comment]
You should probably add the `<path>` element so you get `<model><path archive="y">Models/c172p-detailed-backwards-compatible.xml</path></model>`

**Comment by Juanvvc** [comment]
Thanks, flyingfisch. I think it won't be necessary because I prefer trying the proposals in the forum to avoid the management of two separated XML files. In any case, please, stay tuned in case we need your script next week!

**Comment by flyingfisch** [comment]
Cool, keep up the good work!

**Comment by wlbragg** [comment]
"Thanks, i tried option one and it was a bit glitchy. I'll try option two and let you know how it goes."
Can you elaborate on this, Do you remember what you saw that was glitchy?

**Comment by flyingfisch** [comment]
The branch didn't seem to be up-to-date with the new liveries, the shadow had some z-fighting issues or something, and some things in the cockpit that are clickable in the master branch aren't in that branch.
