### ISSUE TITLE
Map the mixture lever back to /controls/engines/engine/mixture

### ISSUE THREAD

**Issue by Juanvvc** [Juanvvc/c172p-detailed#132]
Currently, the mixture lever is controlled by /controls/engines/engine/mixture-lever as a proxy property, and  /controls/engines/engine/mixture is written by Nasal/engine.nas taking into account this value and (if the engine is off) the number of times the pilot primed the engine.

This was a temporal solution to implement the primer. I tried many times to create a jsbsim module to control this, but I was unable to due my lack of knowledge of jsbsim. Please, check this post: http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=525#p234882

The main problem with our approach is that input devices with a mixture lever (for example, the Saitek Quadrant) must be mapped specifically to /controls/engines/engine/mixture-lever instead of /controls/engines/engine/mixture as in any other aircraft. Forcing a joystick configuration specific to our aircraft is not acceptable, in my opinion.

This bug is my main concern for the c172p-detailed to be accepted as the default aircraft: all input devices must work out-of-the-box as expected. I prefer removing the primer support better than forcing a specific joystick configuration.

Keep in mind everything works ok if you are using a joystick without a mixture lever or the keyboard. If this is your case, you probably didn't notice this bug until now :)

**Comment by dany93** [comment]
I don't understand the problem well, I've never played with this.
However, the p51d (JSBSim, Jim Wilson, Jon Berndt and Hal V. Engel) has a mixture lever and a primer. If I recall well, it has a realistic and demanding starting procedure.
In the files, I see systems/mixture-control.xml.
I do not know if it works with input devices with a mixture lever.
I it can it help...

**Comment by onox** [comment]
So the problem is that the joystick configuration file of Saitek Quadrant uses mixture-lever instead of mixture? While everybody else uses mixture?

**Comment by dany93** [comment]
I haven't understood this.
I've understood that aircraft usually use /engines/engine/mixture, and the joystick configuration file of Saitek Quadrant is fit for this. The problem is that c172p-detailed needs  /controls/engines/engine/mixture-lever. That would need a special configuration for the joystick(s).

**Comment by Juanvvc** [comment]
dany93 correctly understood the problem. Sorry for not being clear enough :)

We require input devices to use mixture-lever instead of mixture, and this is wrong (imho). In the beginning, it was a temporal solution but we are not fixing this. I mapped the keyboard to control mixture-lever, so the keys m/M control mixture-lever and not mixture directly. But we shouldn't change the configuration of all possible devices out there. A user with a Saitek Quadrant, for example, must change the configuration for the quadrant only for our aircraft. And this is going to be the same with any other joystick with a mixture lever.

I'll check the p51d to get some ideas. I strongly believe fixing this bug is urgent if we really want the c172p-detailed to be considered as the default aircraft for the next release of flightgear.

**Comment by onox** [comment]
So the problem is that JSBsim reads mixture, but you want to read it real-mixture (with mixture being the proxy) and that you don't know how to change the FDM?

**Comment by dany93** [comment]
Like you, I prefer coding the features in xml rather by nasal. However, nasal is more flexible and concise for sophisticated functions. Sometimes hard to avoid.
But at this day I'm completely ignorant of what to do for your problem.
I've already used <function name="aero/function/a-name"> inside a FDM (DR400-JSBSim) but here I don't see... (that's my lack of knowledge, not JSBSim itself). How do you feel JSBSim function could help to solve this problem? Maybe if I understood better what you would need, I may be able to help to get a tool?

**Comment by dany93** [comment]
Sorry, my phrase above has been cut.
I've already used <function name="aero/function/a-name"> inside a FDM (DR400-JSBSim)

**Comment by Juanvvc** [comment]
If I understood correctly how jsbsim works (and, probably, I didn't), you can define functions like this:

engine_mixture = position_of_mixture_lever * gravity_factor * engine_correctly_primed

where gravity_factor is a real number in (0,1) and engine_correctly_primed is 0 or 1. These two values can be calculated in Nasal and (somehow) passed to jsbsim. The gravity_factor could be even calculated directly by jsbsim using a table and g_acceleration as input.

Is my description of how jsbsim works correct?

**Comment by dany93** [comment]
Although that is not a FDM, but an engine problem, I think it is possible in the FDM file, to have
    function name="aero/function/kCDge"      
      product
          1st-number
          2nd-number (or a table)
          a-property       
      /product
    /function
(I have deleted the brackets because they don't pass into text)
This gives an ouput = property with the name kCDge, which you can read in the tree.

But I do not understand why this is better than defining this function in nasal. Because you need a table to calculate the  gravity_factor?

**Comment by Juanvvc** [comment]
As far as I understand, flighgear is configured to pass /controls/engines/engine/mixture directly from your input device to the FDM. You cannot modify this property in Nasal if an input device is configured to modify it. You can configure a specific input device to change, say, /controls/engines/engine/mixture-lever and then write a nasal function to calculate  /controls/engines/engine/mixture based on mixture-lever. This is what we are doing now. But, in this case, we must configure ALL DEVICES to write to mixture-lever instead of mixture. This is doable for most devices (there is a nasal function in input.nas for this) but not all input devices are required to use input.nas

This is why I believe we must assume /controls/engines/engine/mixture is changed only by the input devices, passed directly to the FDM and cannot be modified in Nasal. Still, we need a way to calculate the real mixture for the engine and I'm under the impression it can be done in jsbsim. But I'm not really sure :)

**Comment by dany93** [comment]
engine_mixture = normalized_position_of_mixture_lever * gravity_factor * engine_primed
The only problem is the gravity factor, the two others are numbers.
You wish to have:
1) as inputs: (product of)
- normalized_position_of_mixture_lever
- the output value of 2-entries table: g_acceleration and another (?)
- engine_primed
2) output : a property, engine_mixture
True?
I think that is possible (if I understand well).
The question is the table which allows the gravity factor calculation (interpolation).
I presume you have it?

**Comment by dany93** [comment]
"I believe we must assume /controls/engines/engine/mixture is changed only by the input devices, passed directly to the FDM and it cannot be modified in Nasal. Still, we need a way to calculate the real mixture for the engine"
We have a way to calculate this value, but I don't see why JSBSim should have more authority than nasal to overwrite the 'mixture' value sent by the device.

"If you know of some way to NOT passing /controls/engines/engine/mixture directly to the FDM and using another property instead, this could be our solution."
I don't.
I presume that the engine has 'mixture' as input, and that's hard-coded. Maybe a question to ask Jon S. Berndt.
Or find another way to circumvent it, but I don't see.

**Comment by dany93** [comment]
I've retrieved a few notes that I had written (in response to the french forum) about the P51D start procedure.
And I had written that (in FG) the engine started even without primer. Maybe the same problem...

**Comment by onox** [comment]
@Juanvvc I have been reading some of the C++ in `src/FDM/JSBSim/JSBSim.cxx` and `src/FDM/JSBSim/models/FGFCS.cpp`. This is what it seems to do:

1. It executes: `FCS->SetMixtureCmd(i, globals->get_controls()->get_mixture(i));`. It does the same thing for the throttle, prop advance, and feather.

2. Then it copies the mixture cmd value to the mixture pos. This is sort of a safe-mode method.

3. Finally, it executes "system channels".

So from what I read you should read you should probably create a `fcs_function` which reads `fcs/mixture-cmd-norm` and writes to `fcs/mixture-pos-norm`.

The same goes for the other properties:

* `fcs/throttle-cmd-norm` and`fcs/throttle-pos-norm`

* `fcs/mixture-cmd-norm` and `fcs/mixture-pos-norm`

* `fcs/advance-cmd-norm` and `fcs/advance-pos-norm`

* `fcs/feather-cmd-norm` and `fcs/feather-pos-norm`

**Comment by dany93** [comment]
I tried this

            <function name="fcs/mixture-pos-norm">
                <description>for Mixture command by a standard device</description>
                <property>fcs/mixture-cmd-norm</property>
            </function>

(Is it what you want to say?)
But I got:
Property fcs/mixture-pos-norm has already been successfully bound (late).
Fatal error (const char*): Failed to bind the property to an existing already tied node.

Anyway, I don't understand and could not test even if it worked because these two values are already tied and equals in my sim.
I have no mixture lever on my device, I set the mixture with the scroll wheel.

**Comment by dany93** [comment]
I have one idea, which could be the solution but it is rather complicated just to have primer working.
Try the Piper SenecaII: the right engine does not start if the primer has not been activated once ( the left engine starts, weirdly...).
See "Fuel and payload" before doing everything. Tanks 2 and 3 are very small intermediate tanks, tank 3 fills only when you push the primer button.
Important: test this with a standard mixture device. Not your specially programmed one.

I have implemented such a system on the Douglas DC3 JSBSim (in my forum signature). The problem was to feed 2 engines with any of 4 tanks.
I had to create two small intermediate ("collector") tanks, one per engine. I like to compare this with the small tank of a carburettor.
I've written the explanation in the wiki http://wiki.flightgear.org/Howto:Write_a_fuel_system_in_JSBSim#Douglas_DC3_.282_engines.2C_4_tanks.29
My idea (validity to be confirmed):
Only one collector tank would be necessary for the c172 . The engine should be fed by this collector tank instead of the main tank. And the collector tank is itself fed by the main tank, if the main is not empty... and, at start, if the primer has been activated like for the SenecaII.
The difficult part is the nasal code to control this, but  you could see and select what is done in SenecaII (and DC3).
I've done this in 2013, I don't remember well...
Tell me it this is not clear.

**Comment by onox** [comment]
No, I mean this:

```xml
<channel name="Mixture">

    <fcs_function name="fcs/mixture-pos-norm">
        <function>
            <property>fcs/mixture-cmd-norm</property>
        </function>
        <output>fcs/mixture-pos-norm</output>
    </fcs_function>

</channel>
```

**Comment by onox** [comment]
@Juanvvc Do you want it to behave just like it works in `engine.nas`?

**Comment by dany93** [comment]
Can you see for the patch given by wtikky42 in engine.nas?
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=242280#p242280
He had a problem with the mixture which would not work, and we found that it was because he started with fuel_freeze=true.
I don't understand more for the patch....

**Comment by wkitty42** [comment]
thanks for the mention dany93... even with crossed fingers (wkitty42) ;)  

yes, the patch provided simply moves the current mixture code in the update loop to the top /above/ the fuel_freeze abort code... the only other thing in there was the need to split out the outOfFuel check so that it remained below the fuel processing code... so now the code flow is

  mixture processing -> fuel_freeze check -> fuel processing

with the patch i can now get over 8400 alt without the EGT going full cold... currently, since i made the patch changes, my c172p-detailed is still flying at 13500 alt, 110 ikts (134 gkts), 63% mixture... before the patch, mixture was never processed when fuel_freeze was true... now it is... the patch just needs to be checked to work properly with fuel_freeze false and running out of fuel...

**Comment by onox** [comment]
Fuel freeze check removed in branch [bug-132](https://github.com/Juanvvc/c172p-detailed/commits/bug-132)

I'll remove the usage of mixture-lever and use JSBsim tomorrow.

**Comment by dany93** [comment]
I have a first version for the fuel management.
See http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=242612#p242612
I have sent a link  with 3 files http://www.mediafire.com/download/i7cczkaet7vqrnq/C172p_Fuel-syst-20150512.7z
