### ISSUE TITLE
Turn coordinator buggy colour

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#146]
Dany93's turn coordinator has some strange colour when the sun is setting or at night, using ALS mode. 

http://s12.postimg.org/apn9lvz65/TC_bug.png
http://s11.postimg.org/ji5njhboj/fgfs_screen_001.png
http://s3.postimg.org/t2i50zf83/fgfs_screen_001.png

**Comment by wlbragg** [comment]
What do you mean dany's TC? Is this in master too? Was it a replacement from dany's FDM to master? I'm only asking because on the forum it's been determined the cause is an inherited effect no other guage is using. So the quick fix is to remove the effect.

**Comment by gilbertohasnofb** [comment]
Some time ago, Dany replaced our TC by one that he had previously made for the default c172p. The main improvement was concerning the TC ball, which was resized and recoloured. I have the impression that this bug I am reporting here didn't exist before Dany replaced our TC, but I may be wrong.

**Comment by dany93** [comment]
I have tried again the c172p-detailed I had dowloaded on 27 march 2015.
On this, the orange-colored effect under Rembrandt does not appear because the

    <inherits-from>Effects/model-transparent</inherits-from>    

has been commented.
But the "dirty" effect on the glass tube (see my post and image on the forum)
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1230#p241755
 appears, although maybe slightly less.

ludomotico may well have given the explanation
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1230#p241756

**Comment by dany93** [comment]
I have tested again the c172p-detailed I had downloaded on 27 march 2015.
On this, it's worst, the orange-colored effect under Rembrandt still appears even though the

    <inherits-from>Effects/model-transparent</inherits-from>    

has been commented.
Moreover, he "dirty" effect on the glass tube (see my post and image on the forum)
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1230#p241755
also appears, although maybe slightly less.

ludomotico may have given the explanation
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1230#p241756

**Comment by wlbragg** [comment]
Will this work?
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=241847#p241844

**Comment by wlbragg** [comment]
Note ludomotico reply,
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1260#p241852

**Comment by onox** [comment]
Why is it that only the TC has this problem? :cry: 

![fgfs-screen-185](https://cloud.githubusercontent.com/assets/3361585/8470777/d25f57d4-2090-11e5-80b2-1867d847c121.png)
![fgfs-screen-186](https://cloud.githubusercontent.com/assets/3361585/8470778/d25ff054-2090-11e5-8a53-f2db6f3e7c68.png)

**Comment by onox** [comment]
@dany93 @wlbragg Do you know what's going on with the TC?

**Comment by wlbragg** [comment]
I'm not sure but in the tc.xml, I think it is the only instrument that is using 
```
<inherits-from>Effects/model-transparent</inherits-from>
```

**Comment by onox** [comment]
@wlbragg It looks like that is causing the problem indeed.

**Comment by onox** [comment]
@wlbragg `kt76a/kt76a.xml`, `kx165/kx165-1.xml`, and `kx165/kx165-2.xml` are using `model-transparent` as well, but don't have the same problem.

**Comment by dany93** [comment]
The problem (never solved) is that,
- **without** 
```xml
<inherits-from>Effects/model-transparent</inherits-from>
```

we have this "dirty effect on the ball tube

![tc_rembrandt](https://cloud.githubusercontent.com/assets/11994061/8511353/bb0d04fe-2311-11e5-9a39-665078d9266a.png)

http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1230#p241755

- and **with it**, we have the buggy color under Rembrandt...

This is [from the beginning](https://github.com/Juanvvc/c172p-detailed/issues/146#issuecomment-99420029).
If [Ludomotico is right](http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=1230#p241756), it comes from a transparent surface or a texture with an alpha channel in Blender (??)

**Comment by onox** [comment]
That looks like a very old screenshot. This is how it currently looks:

![fgfs-screen-207](https://cloud.githubusercontent.com/assets/3361585/8514700/8246b960-2395-11e5-8b90-0c63e2a16af5.png)

**Comment by wlbragg** [comment]
That ugly  ball tube was just that an "ugly ball tube graphic", I think it was finally replaced with a clean one!

**Comment by onox** [comment]
This is how it looks in Rembrandt:

![fgfs-screen-205](https://cloud.githubusercontent.com/assets/3361585/8515084/0b21b8a6-239c-11e5-8dad-72f039f4e5c0.png)

The tube is a bit ugly indeed. I think this is small price to pay in order to have a nice pretty plane in ALS. But people who use Rembrandt don't care about prettiness anyway, since the atmosphere is super ugly and aircraft don't have anti-aliasing (aliasing = lines are staircased) :stuck_out_tongue_closed_eyes:

**Comment by wlbragg** [comment]
You know what though, fixing that ugly tube is a matter of removing that ugly texture from it. I don't think it is necessarily needed in Rembrandt or adding anything to it anyway. I thought someone (even me) had cleaned it up. I know I posted something showing what it looked like cleaned up.

**Comment by wlbragg** [comment]
Yes here it is.
http://forum.flightgear.org/viewtopic.php?f=4&t=25157&p=241844&hilit=TC+glass#p241844

**Comment by onox** [comment]
If you can make sure it still looks nice in ALS, then sure :smile:

**Comment by onox** [comment]
Can you do this in bug-146b?

**Comment by onox** [comment]
Or just bug-146 if you find that easier.

**Comment by dany93** [comment]
@onox wrote
>The tube is a bit ugly indeed. I think this is small price to pay in order to have a nice pretty plane in ALS

I agree. I added my remark just for you to notice it. If you accept it like this, I do not consider it as an important issue, neither.

**Comment by wlbragg** [comment]
I took a look at it again and tried to clean up the tube, my problem is I'm not sure I am getting good visuals with Rembrandt. I'm getting very inconsistent results, or more like consistently "bad" results.

The one thing I think I noticed was I got the "pink" glow color using Rembrandt with the inheritance on, but only on that instrument. I guess because it is one of the few that use it.

So this issue just isn't on my priority list. I can't use Rembrandt so I really can't program for it.
I'm done with it.
As far as  am concerned, we can leave it to a Rembrandt buff to clean it up if they wish.

**Comment by onox** [comment]
That's fine with me, we'll leave the issue closed.

**Comment by wkitty42** [comment]
FWIW and TBH, with the state that rembrandt is in, being undeveloped and basically nothing being done with it at all, i'd say to just drop it and don't worry about it... slowly and surely, rembrandt is being left in the dust... those that continue to try to develop for it are wasting their time... yeah, i'm seeing this in the 6 months i've been here and it is an observation based solely on activity...
