### ISSUE TITLE
ALS landing light on at startup

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#169]
This may be tied to issue #103. It also may be intermittent.

**Comment by gilbertohasnofb** [comment]
I don't understand this bug, do you mean that the ALS landing light is always on regardless of its switch on startup? Or is your switch always on regardless of its last state? On my system neither of these two possible problems I just mentioned are present, the light works just fine.

**Comment by wlbragg** [comment]
Now I am not sure what was happening. When you start up even if the switches are on the lights should be off until you either click on autostart or master on, right?
My ALS landing light were on at startup, (yes the Landing Light switch was on), but they still should have been off.
I just tested it and now it is working correctly, they are off whether or not the switch is on until I autostart or master on. I did notice the master switch in NOT persistent, is that correct?

**Comment by gilbertohasnofb** [comment]
Yes, the master is not persistent (which is probably a good idea since we planned to implement battery drainage :wink: ). So since now it's working correctly, let's probably close this issue but we keep an eye on it, and reopen if it ever happens again.

BTW, the bug I see with ALS landing lights (and also taxi lights) is that they disappear when the aircraft is moving or when the throttle is above a certain amount. Did you ever encounter this bug? I had no problems before, but since no one seems to see this it may be some problem with my ATI card...

**Comment by wlbragg** [comment]
"throttle is above a certain amount"
Yes, that is what made me notice it in the first place. i think maybe that is what broke it and put it in a condition that caused the other problem?

**Comment by gilbertohasnofb** [comment]
Okay, so you also see this bug! Strange, I wrote about it in the forum but I had the impression I was the only one seeing this. In that case, I will open a new issue for it.

See: https://github.com/Juanvvc/c172p-detailed/issues/174

**Comment by wlbragg** [comment]
Lets close this and go to #174
