### ISSUE TITLE
Damage and instruments are not recorded in the flight recorder

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#237]
Properties that reflect the damage should be recorded in the flight recorder. Instruments should be recorded as well.

Fixing it in branch [bug-237](https://github.com/Juanvvc/c172p-detailed/tree/bug-237).

* [x] Primer
* [x] Master Battery (already working)
* [x] Master Alternator (already working)
* [x] Magneto's (already working)
* [x] Starter (one position further than the magneto's)
* [x] Throttle (already working)
* [x] Mixture (already working)
* [x] Instrument lighting
* [x] Carb Heat
* [x] Pitot Heat
* [x] Cabin Heat slider
* [x] Cabin Air slider
* [x] Navigation Lights
* [x] Beacon
* [x] Strobe
* [x] Taxi Light
* [x] Landing Lights
* [x] Compass
* [x] Fuel selector switch
* [x] Elevator trim wheel
* [x] Heading bug
* [x] Doors
* [x] Passengers/baggage weight
* [x] Circuit breakers
* [x] Selected gear
* [x] Position of gear (for amphibious variant)
* [x] Smoke and sparks

It looks like the needles of the instruments are already working. Somebody should double check this.

Not implemented:

* Some extra environment conditions used by cabin temperature popup tip (Requires some refactoring to store its state in properties instead of Nasal variables)
* Time (There's not really a timestamp in the property tree. There's a `warp` property, but it doesn't work correctly during replay)
* Radio stack switches and dials (Will be done later)

**Comment by onox** [comment]
@wlbragg Which properties control the yellow sparks and grey dust when tail and/or wings touch the ground?

**Comment by wkitty42** [comment]
if this is what i think it is, we should also record the selected gear... there's numerous times that i'm on the lake and CTRL-R to replay which puts me back on the tarmac with no wheels... the floats, at least, are showing ""smoke"" streaming from them and if i switch to wheels, the smoke is still streaming even after i get into the air... at some point it stops but i've not been able to track down when... it may be when i switch back to pontoons of some type... i really don't know because i haven't mastered flying the craft while looking at it from the heli view beside it as we fly ;)

**Comment by onox** [comment]
Good point, @wkitty42.

**Comment by wlbragg** [comment]
"Which properties control the yellow sparks and grey dust when tail and/or wings touch the ground?"

fdm/jsbsim/contact/unit[??]/WOW and velocities/groundspeed-kt in most cases.

**Comment by onox** [comment]
@wlbragg Thanks. I have added them here locally. Smoke, sparks, and wakes are working.

**Comment by wkitty42** [comment]
and gear changes?  yeah, i know we shouldn't be changing gear in mid-flight but i'm sure it will be happening unless we specifically set up a block to prevent it at some point before power up and takeoff... maybe that's an idea to consider so that the reply from pontoons on water doesn't toss us back on the tarmac with smoke and sparks since we wouldn't be able to change gear in flight or even while making the takeoff roll...

**Comment by onox** [comment]
It's on the todo list :smile_cat:
