### ISSUE TITLE
Trim indicator needle should be easier to see

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#241]
It's dark over dark red. The needle should be white.

Also I noticed rotating the trim wheel on some angle the texture disappears. These with OH-CTL livery.

**Comment by dg-505** [comment]
For me the trim indicator needle is white: 
![trimwheel](https://cloud.githubusercontent.com/assets/12293276/8006523/07b0a0c0-0b95-11e5-9489-66b0224d8f8a.JPG)

Also I don't see any textures disappearing when rotating the trim wheel...

**Comment by gilbertohasnofb** [comment]
I see the same as dg-505 above.

**Comment by wkitty42** [comment]
i see the white line but the wheel texture goes away at two points of the range... on the positive side going from 0.02 to 0.03 and on the negative side going from -0.05 to -0.06... here's pics...

0.02 - has wheel texture
![fgfs-screen-043](https://cloud.githubusercontent.com/assets/4641713/8007718/cb55f8ec-0b6b-11e5-8df4-11a51db99bf4.png)

0.03 - no wheel texture
![fgfs-screen-044](https://cloud.githubusercontent.com/assets/4641713/8007719/cb5880da-0b6b-11e5-882d-61b8d7f4c608.png)

-0,05 - has wheel texture
![fgfs-screen-045](https://cloud.githubusercontent.com/assets/4641713/8007720/cb5bc466-0b6b-11e5-94e3-d2474de95f5e.png)

-0.06 - no wheel texture
![fgfs-screen-046](https://cloud.githubusercontent.com/assets/4641713/8007721/cb608e60-0b6b-11e5-9976-2a8813b3de40.png)

**Comment by dg-505** [comment]
Can't confirm this... :confused: 
Don't know why you have this bug...

**Comment by gilbertohasnofb** [comment]
@wkitty42 maybe open a new issue for the trim wheel bug, because this one is about the needle only, so this way we keep it more organized and it will be easier to fix it.

**Comment by wkitty42** [comment]
i'll open a new issue and reference this one for the pictures... i was going by @tigert second line in the original issue text... this is also with the OH-CTL as noted... i've not looked at any others yet...

**Comment by tigert** [comment]
Okay. I will need to verify this - somehow it is not very easy to see on my setup.

**Comment by tigert** [comment]
Okay, actually it is white for me too, so there is no real bug, the indicator is just very thin and thus currently it is hard to see. We should make it thicker, so it is more useful in practice.

http://tigert.1g.fi/kuvat/Simulators/Flightgear/C172-dimensions/aae.jpg/_full.jpg 

//Tuomas

**Comment by Juanvvc** [comment]
If I recall correctly, both the wheel and the indicator are not textured but they have a plain color. Objects with plain color are very sensitive to ambient light. Under certain angles, illuminated and not illuminated faces may be rendered with the same grey color. The effect is that these faces cannot be distinguished and details "disappear". Actually they don't, it is just they are of the same color.

I'll check if this is the case. The simplest solution is probably assigning a texture to the wheel. I'll also check the trim indicator, it may be too small.

**Comment by gilbertohasnofb** [comment]
> The simplest solution is probably assigning a texture to the wheel. I'll also check the trim indicator, it may be too small.

What if we assign a full white texture to the needle? Would that help or it wouldn't make any difference? As for the trim wheel, I can prepare a small black texture for it if you want.

**Comment by Juanvvc** [comment]
The high dependence with the ambient light is an issue for all untextured, dark objects. A white texture for the indicator won't make any difference in this case.

(Please, keep in mind this is only a guess after checking your snapshots! I can be wrong!)

**Comment by gilbertohasnofb** [comment]
Ok, Juan! As for the trim wheel texture, should I simply make some kind of plastic black texture or should I try to imitate the pattern seen here?: https://cloud.githubusercontent.com/assets/4641713/8007720/cb5bc466-0b6b-11e5-94e3-d2474de95f5e.png

**Comment by wkitty42** [comment]
on the trim wheel texture... it sure looks like there's a texture on it to me... something that makes it look like there's big knurls for your fingers to fit in when you move it... the pics i posted show it pretty easily... it just looks like it may not be applied to the entire wheel or that it is visible when at certain view angles and not at others...

**Comment by Juanvvc** [comment]
wkitty42, I think you confuse "texture" with "vertices". These knurls you mention are modelled using vertices, and this is ok. Now, you have to paint the object (main wheel and knurls). You can use a solid color or a texture like. Using solid colors is much faster and easier, but it makes the surface look undetailed and (specific to FlightGear) it has issues with the not-illuminated faces. Using textures is more laborious but the results are nicer. As a modeller, you have to decide if the nicer result make up for the extra work.

I can confirm the trim wheel DOESN'T have a texture :) It has a solid color (0.122, 0.122, 0.122) and an ambient parameter of 0.115. This means illuminated and non-illuminated faces have nearly the same color.

The trim wheel is one of the few objects in our aircraft that still use plain colors. Other object that use plain red are the fuel caps on the wings. Check their shadowed faces under several light conditions to understand this issue better.

Gilberto, the whell does not need any complex texture. A simple 2x2 image with a plain gray color is perfectly OK! The issue appears because plain colors and PNG textures are managed differently in FlightGear. Shadows on image textures are much more realistic even if they use only plain colors! In fact, I'll take advantage of this situation and I'll try to use Thorsten piece of advice for texturing objects using only noise.

**Comment by wkitty42** [comment]
@Juanvvc you may be right... most likely you are... i only know that i saw the knurls there and then they disappeared as i moved the wheel... if there's no texture on the wheel, i guess the problem is something else... should i close my issue created for that part of the problem or leave it open since this one is about the white line? i was asked to open a separate issue because of that...

**Comment by Juanvvc** [comment]
Yes, they are two separated issues. My bad for commenting here about the other trim wheel issue :) Keep both open, I'll check them.

**Comment by wlbragg** [comment]
FYI, whenever there is a visual issue regarding instruments make sure you are aware of the shadow that is being cast from internal shadow effect. Because that now effects most instruments.

**Comment by gilbertohasnofb** [comment]
> Gilberto, the whell does not need any complex texture. A simple 2x2 image with a plain gray color is perfectly OK! The issue appears because plain colors and PNG textures are managed differently in FlightGear. Shadows on image textures are much more realistic even if they use only plain colors! In fact, I'll take advantage of this situation and I'll try to use Thorsten piece of advice for texturing objects using only noise.

Done, see Models/gray-square.png. This same texture could also be applied to the back of the propeller (see https://github.com/Juanvvc/c172p-detailed/issues/157). Let me know if you need anything else.
