### ISSUE TITLE
trim wheel texture disappears

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#250]
When rolling the trim wheel, the texture disappears and reappears at certain settings... this happens with all liveries... it is not limited to just one livery... the numbers at the points where the texture disappears or comes back are not the same across all liveries, though... I thought it might have been number related or maybe length/wrapping but I don't know now...

See issue #241 for some reference pics I posted... more can be posted if needed...

**Comment by Juanvvc** [comment]
Please, see my comments to #241 I'll check this as soon as possible.

**Comment by gilbertohasnofb** [comment]
Texture created as Models/gray-square.png. This same texture could also be applied to the back of the propeller (see #157). Let me know if you need anything else.

**Comment by gilbertohasnofb** [comment]
Could someone with knowledge of Blender apply this texture to the trim wheel to see if it solves the problem? Would you have the time to check this out, @dg-505 ?

**Comment by gilbertohasnofb** [comment]
Also see #253.

**Comment by Juanvvc** [comment]
This is much trickier to fix than I expected. Gilberto, your gay_texture.png texture did not fix this issue. It seems to be related to the c172p-interior effect. That is, the effect that produces shadows inside the cabin. It seems the shadows are calculated *before* the wheel rates, and then shadows also rotate with the wheel.

One easy fix is not applying the shadows to the trim wheel. For me it is ok because it is already a dark object and shadows are not very noticeable on dark objects. But the effect artists must decide if they are ok with NOT applying the c172p-detail effect on the WheelTrim object.

**Comment by gilbertohasnofb** [comment]
> Gilberto, your gray_texture.png texture did not fix this issue. It seems to be related to the c172p-interior effect.

In that case, I will remove both `gray-texture.png` and `light-gray-texture.png`.

> One easy fix is not applying the shadows to the trim wheel. For me it is ok because it is already a dark object and shadows are not very noticeable on dark objects. But the effect artists must decide if they are ok with NOT applying the c172p-detail effect on the WheelTrim object.

I am also absolutely all right with the proposed solution. So let's just see what @wlbragg has to say about it since he is the one whom implemented the shadows.

**Comment by onox** [comment]
@Juanvvc @gilbertohasnofb Isn't this just a matter of apply the texture to the backside of the wheel as well? (The 180 deg to 360 deg part) It seems with some positions of the trim wheel, that it looks ok with ALS on, but if I move it a little then it becomes fully grey.

**Comment by gilbertohasnofb** [comment]
I honestly don't know :disappointed:

**Comment by Juanvvc** [comment]
That was my initial guess, but currently I think it is not a problem with textures. In fact, the TrimWheel object is not textured, it has a plain color.

I run some tests and I think the problem is that shadows are calculated BEFORE rotations. The part inside the panel is obviously not illuminated, so when the wheel is rotated and thar part comes to the foreground, it seems black.

I don't know if you can apply rotation and then shadows. Moving the rotation animation after the c172p-interior effect if the XML did not make any difference.

One simple solution is just NOT applying shadows to the TrimWheel. That is, removing line 386 deom c172p.xml ( https://github.com/Juanvvc/c172p-detailed/blob/master/Models/c172p.xml#L386 ) This issue is fixed but the TrimWheel won't have any shadows. This is ok for me because it is already a dark object and not having shadows won't make a big difference. But the lack of shadows is noticeable under some light conditions, so we must decide it this "fix" is ok, at least for the upcoming release.

**Comment by gilbertohasnofb** [comment]
> That was my initial guess but now I think it is not a problem with textures. In fact, the TrimWheel object is not textured, it has a plain color.

If you want to apply texture to it, I can add that dark grey square texture back to the Model folder. Would that help with this issue?

> One simple solution is just NOT applying shadows to the TrimWheel. 

I also think this is an acceptable solution, the trim wheel is a dark object and it won't make much difference anyway.

**Comment by Juanvvc** [comment]
> If you want to apply texture to it, I can add that dark grey square texture back to the Model folder. Would that help with this issue?

I'm afraid it wouldn't. We already tried that.

**Comment by gilbertohasnofb** [comment]
So let's maybe try removing the shadows, at least for now. If the result is acceptable in most situations, then it will be better than what we currently have.

**Comment by onox** [comment]
Removing line 386 clearly fixed the issue, and I couldn't really notice the shadow anyway, so I'll push a fix in a minute.

**Comment by onox** [comment]
> I run some tests and I think the problem is that shadows are calculated BEFORE rotations. The part inside the panel is obviously not illuminated, so when the wheel is rotated and that part comes to the foreground, it seems black.

That could be the problem indeed. When I rotate the wheel until it looks weird, then if I zoom in, I can still see the trim wheel, but it is covered by something very dark.
