### ISSUE TITLE
Wheels of amphibious do not rotate

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#311]
1. [x] The wheels of the amphibious gear do not rotate. Not even in singleplayer.

2. [x] Object RightWheel uses `gear/gear[1]/rollspeed-ms`, but should be using `gear/gear[2]/rollspeed-ms`

3. [x] `rollspeed-ms` is not transferred automatically, so we should do aliasing again.

We should decide how many properties we want to alias. If you want to send `rollspeed-ms` over MP for each gear, then we would have to alias 7 properties (3 for default + 4 for pontoons). We can also use the `/velocities/groundspeed-kt` property for the nosegear (1 for default + 2 for pontoons). That will result in 5 properties (`groundspeed-kt` + 2x `rollspeed-ms` for default + 2x `rollspeed-ms` for pontoons)

**Comment by wlbragg** [comment]
OK, I'll take a look at it.
Don't know how we (I) overlooked that in single player.

**Comment by wlbragg** [comment]
Well, this is not a simple fix. The wheels on amphibious were never designed do rotate, the trailing arm, axle and wheel assembly appear to be one solid piece. So I will see if I can correct this in blender, it may be over my pay grade!

**Comment by wlbragg** [comment]
OK, I managed to fix the front wheels. I imported the front wheel and axle off of the default landing gear, sized them, duplicated and positioned them. The spin around the axis is really close but not perfect, I don't know how to get the exact numbers?

Next the back.

**Comment by onox** [comment]
Use Blender to get the coordinates? :smile:

**Comment by onox** [comment]
@wlbragg In master the front gear are now visible with the regular pontoons.

@gilbertohasnofb @wlbragg I can save the 2 commits above v3.6, reset and force push if that's ok with you.

**Comment by onox** [comment]
@wlbragg I have pushed a new branch bug-311 with both of your two commits. You can ditch the old amphibious-rear-wheel-animation-311 branch.

**Comment by wlbragg** [comment]
Thank you for reorganizing the branches, I'll try to pay more attention to organization before diving in.

OK, I see I missed factoring out the new "front" wheel objects in the pontoon condition, other than that, on that commit what else was wrong that you didn't want to leave it? Was it because you think we should use this locked-track animation instead? Is that used anywhere else in the c172p?
If not, why do you want to use that particular method on only this one group of objects verses the "standard" way everything else is done? Or am I misunderstanding what the locked-track animation is?

That the second PR wasn't ready, (I knew that and requested and got guidance), in the future I'll just post the branch and not make it a PR until it is ready.

I got schooled by my kid just now and he was smart enough to point out how to find and use the coordinates in blender. My problem was I appended these objects from another aircraft .ac and all the objects origins were not set to geometry and were set to some abstract point. Now that I know that little hopefully this is going to go a lot easier. 
I'll keep working on it.

"B" was a typo.

**Comment by onox** [comment]
This locked-track animation is supposedly used to easily get a scissor animation (the upper part, strut, + lower part, damper).

What I do to read coordinates is: you click on an object in the tree, then expand that object in the tree (click the + symbol or something) so that the tree will show you another object as a child of the previous object. Click that object and then press shift+s. Blender will show you a context menu and there you can tell Blender to set the 3D cursor to the center of the element. Then read the coordinates of the 3D cursor.

I notice though that some objects do not have a good center.

**Comment by onox** [comment]
I've aliased the `rollspeed-ms` properties and created PR #318

**Comment by wlbragg** [comment]
Cool, I'll check it.
