### ISSUE TITLE
Animate pontoon rudders

### ISSUE THREAD

**Issue by wlbragg** [Juanvvc/c172p-detailed#344]
Tie pontoon rudders in with rudder peddles?
Also add corresponding FDM turning in water improvements.

**Comment by onox** [comment]
Isn't animating the rudders just a bug? Should 3.6 IMO.

What do you mean with the FDM improvements?

**Comment by wlbragg** [comment]
The rudders should allow the craft to make tight turns in the water, they should effect the steering. Yeah, it's a bug!

**Comment by dany93** [comment]
I searched in hydrodynamics.xml (lines 655 - 669)

```
  <fcs_function name="hydro/rudder-yaw-moment-lbsft">
   <documentation>
    Guessestimated yaw moment due to water rudder.
   </documentation>
   <function>
    <description>Hydrodynamic yaw moment due to rudder</description>
    <product>
     <property>/controls/gear/water-rudder-down</property>
     <property>hydro/qbar-u-psf</property>
     <property>hydro/float-beam-ft3</property>
     <property>fcs/rudder-pos-norm</property>
     <value>-0.025</value>
    </product>
   </function>
  </fcs_function>
```
Changing the `<value>` (factor) does nothing.
But I see
`     <property>/controls/gear/water-rudder-down</property>`
Its value is `0`, I cannot  change it even manually by "set" in the properties.
How can we set these rudders to "down?"

**Comment by onox** [comment]
@dany93 It's `/controls/gear/water-rudder` that you need to control! :smile:

**Comment by onox** [comment]
This reminds me also that `/controls/gear/water-rudder-down` is not transmitted over MP and saved by the flight recorder.

**Comment by dany93** [comment]
>It's /controls/gear/water-rudder that you need to control! 

OK (oups...)
In this case, it works, isn't it?
This is just a matter of **how to set them down** and possibly to set the value for their efficiency.

In `Models/c172p.xml` (lines 5751, 5787), the animation should be done by `controls/gear/steering` which remains at 0.
The lines have been commented  which is a hint for an issue ( @wlbragg ?) .
Maybe, they must be animated conditionally, only when they are down?

**Comment by wlbragg** [comment]
>Maybe, they must be animated conditionally, only when they are down?

You know what, you may be right. They never rotated correctly so I commented them out. But I don't think I ever tried it in the down position.

I changed the numbers on the water-rudder-down animation and remember getting it real close and way better than it was. I totally forgot about it and the need to animate it until now.

I guess they would eventually be controlled by the new gear down panel?

**Comment by dany93** [comment]
>I guess they would eventually be controlled by the new gear control panel?

Not the most likely. They need a control even with floats, not only amphibious.

**Comment by wlbragg** [comment]
Yeah right, forgot about pontoon only.

**Comment by dany93** [comment]
For the animation, I think that something is lacking between the rudder command and `controls/gear/steering` because `steering` remains at 0 even when they are down.

**Comment by wlbragg** [comment]
Yes, I don't think it was ever added. I grabbed this whole system from dhc2.

**Comment by dany93** [comment]
Why not animate directly from the aircraft rudder? Whatever they are up or down.
It can be real, I think having seen, on a video, a cable between the tail rudder and the pontoons rudders. It doesn't bother if they rotate in flight.

`Models/c172p.xml`, lines 5751 and 5787
```
  <animation>
    <type>rotate</type>
    <object-name>RHrudder</object-name>
    <object-name>RHrudderArm</object-name>
    <!-- <property>controls/gear/steering</property> -->
    <property>controls/flight/rudder</property>
    <factor>30</factor>
```
```
  <animation>
    <type>rotate</type>
    <object-name>LHrudder</object-name>
    <object-name>LHrudderArm</object-name>
    <!--  <property>controls/gear/steering</property> -->
    <property>controls/flight/rudder</property>
    <factor>30</factor>
```
Also notice `<factor>+30`, changed

The rotation axis is not well-placed, it remains to be adjusted (Blender coordinates?)
And controls/gear/water-rudder (bool) to lower them and make them active for steering.

**Comment by onox** [comment]
What about only doing the rotate animations if `/controls/gear/water-rudder-down` equals 1.0? Then they will only rotate if in the water.

**Comment by dany93** [comment]
I made this to propose and check a solution, and I took the easier.
Anyway, as I wrote I think possible that they rotate even in up position in RL. I do no not know (except maybe this video I do not remember where). Even in RL it is more simple (cables) and it does not bother.

**Comment by wlbragg** [comment]
I think we should try to verify if it moves regardless of on water or not (I'll bet it does) and model it accordingly.

**Comment by dany93** [comment]
When I see this (from the 1982 POH), it goes for the rudders pivoting even in up position.
![c172-float-rudders2015-06-27](https://cloud.githubusercontent.com/assets/11994061/8391340/1e386ec2-1cc0-11e5-8e0b-b7a0f819a5d8.png)

**Comment by wlbragg** [comment]
Looking at that it doesn't rotate left/right at all only up and down. Do these rudders only keep the back end form sliding, not used for steering?

**Comment by wlbragg** [comment]
I think this is just a model but this the only way I can see it working if it is steerable.
http://www.seaplanesupply.com/Water%20Rudder.jpg

**Comment by dany93** [comment]
Of course it is steerable. This is a scheme, the figure title is "Water Rudder Retraction System". Just to explain the *retraction*.

**Comment by wlbragg** [comment]
>This is a sketch, the figure title is "Water Rudder Retraction System". Only to explain the retraction.

You also have the sketch for steerable?

>Of course it is steerable.

The one you have the diagrams for may be, but that doesn't mean they all are. I don't know if they are or aren't or come both ways.

The second picture I posted looks like it is not steerable.

If it is both steerable and can be dropped remotely then it would have to have two (maybe three) cables.

**Comment by dany93** [comment]
http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf
pdf pages 233 - 234 / 357
![c172-water-rudder-syst2015-06-28 00 01 00](https://cloud.githubusercontent.com/assets/11994061/8394091/97fea6d6-1d29-11e5-9917-02c19c4514cf.png)
![c172-water-rudder-steering-p 234-2015-06-28 00 02 18](https://cloud.githubusercontent.com/assets/11994061/8394093/a085c532-1d29-11e5-82bd-abbda23fc103.png)
**They are steerable** (the contrary would have been a nonsense)
But notice that **they are locked in the centered position when they are retracted**.

**Comment by tigert** [comment]
That aileron/rudder interconnect spring installation is interesting. Was that required for c172 float conversios? Maybe uncoordinated turns are so big hazard that the float version behaves worse than you expect, and the springs are added to make the plane avoid the worst of them?

I found this remark: https://www.backcountrypilot.org/forum/tailwheel-training-10718

"The 1973 and newer C 180J and 180K and C A185F equipped with the factory float kit or ski kit have an interconnect between the aileron and rudder cables. It is located on the aft side of the station 65 bulkhead (rear door post) below the floor. Unless disconnected during a float to wheel change over at the operators choice it is approved to be retained while on wheels. These models are also required to have one of two types of rudder centering spring systems located on the inside of the upper skin of the aft fuselage. These may be removed when on wheels but are required for floats or skis as is the aileron rudder interconnect. I became well educated on this system when I tried to install a set of Fluidyne C3200 wheel skis on a 1973 A185F I owned with the belly center line photo port. The photo port required the rudder cables to be rerouted around each side in addition to rerouting the elevator and trim cables. This made the configuration of the rudder cables incompatible with the aileron rudder interconnect. Since the aileron rudder interconnect and rudder center springs are require by the ski installation drawings, I was unable to complete the installation. These are not required on the earlier model 180/185. Sorry for the long post."

This would require some fdm or controls xml work to mix in a bit of rudder for aileron controls?

Good to keep in mind for the tailwheel mod also.. :)
