### ISSUE TITLE
Main gear damage is unrealistic

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#348]
While it is nice and adds the "oops" feeling to a heavy landing, the main gear in a c172 is very very strong and our damage modelling is actually unrealistic.

https://www.youtube.com/watch?v=O1yWkbJuqkE#t=420

We discussed this at the club and remembered this video from NASA Langley research center, which is scary, sobering and very much shows how strong a c172 is (to a point, like everything is).

See at 7 minutes and onward what the gear can take. We could model a burst tire though, and then change the drag on the contact point to make it skid?

**Comment by dany93** [comment]
Several people (you among others, for the nose wheel if I recall well) found that the wheels were too hard at breaking.
Everything is in `Nasal/physics.nas` (lines 200 - 350, it depends on your version).
```
# GROUND DAMAGES

    force0 = get_gear_force(0, 1800, 600); # MUST be the same coefficients as spring_coeff and damping_coeff in the FDM for NOSE
    force1 = get_gear_force(1, 5400, 400); # MUST be the same coefficients as spring_coeff and damping_coeff in the FDM for LEFT gear
    force2 = get_gear_force(2, 5400, 400); # MUST be the same coefficients as spring_coeff and damping_coeff in the FDM for RIGHT gear

    gear_side_force = getprop("/fdm/jsbsim/forces/fby-gear-lbs");
    
#    # For tests: forces (LBS) exerted on gears (along Z and Y), uncomment these lines.
#    if(force0 > 1000) print("Nose Z-force =", force0); #future breaking forces for gears
#    if(force1 > 1200) print("Left Z-force =", force1); #1500 - 2000 lb seems plausible. Mind full load and cross wind landing
#    if(force2 >1200)  print("Right Z-force =", force2);
#    if(gear_side_force > 500) print ("left side-force =", gear_side_force);
#    if(gear_side_force < -500) print ("right side-force =", abs(gear_side_force));

	if(force0 > 1400)
		nosegearbroke();

	if(force1 > 2000 or gear_side_force > 1500)
		leftgearbroke();

	if(force2 > 2000 or gear_side_force < -1500)
		rightgearbroke();
```
force0 is for the nose (in lbs). Currently breaks at 1400 lbs.
force1 and force2 for each main gear. Currently 2000 lbs each.
If you know how much they hold, we enter the values. Very easy.
If you do not know how much, you change the values and do tests. Then tell us.

You can do the tests by displaying the forces. Delete the *six* `#` *at the beginning of the lines* (six, not seven), and you will have the forces displayed in the FG console (above a threshold). You can uncheck damages, increase the 1400 or 2000 thresholds if you want to read the forces without breaking.

**Comment by tigert** [comment]
Yeah, I tried to play with the nosewheel physics, problem was finding the balance between not breaking at brakes-on-and-full-throttle but still breaking on porpoise. As it is currently modified by the amount of the strut compression.

i will need to think and look what kind of atuff the fdm exposes. Side loads are one thing too, straight constant force is less of a problem than a jolt sideways on a bad crosswind landing for example.

Interesting stuff, By no means I d not intend to bash your work, rather than trying to think the ways to model the physical stuff in the sim.

**Comment by onox** [comment]
@tigert I have just moved the gear damage logic to JSBSim. The reason is that the `Nasal/physics.nas` does polling only 0.25 seconds. I have now moved the logic to `Systems/c172p-damage.xml`.

The advantage of doing it in JSBSim is that when the force becomes greater than the limit, the gear will break immediately. Doing it in Nasal has the disadvantage that you might miss the moment that the force is greater than the limit. In practice this means that the nose gear's peak force needs to be much higher so that it is always greater than the limit in a 0.25 seconds duration.

In other words it's now much easier to tune the limit because you're not affected by this 0.25 seconds polling duration.

If you look at line 78, you will see `damage/force-nose-gear GT 1400.0`
If you look at line 95, you will see `damage/force-left-gear GT 2000.0`.
If you look at line 113, you will see `damage/force-right-gear GT 2000.0`.

To see the actual forces while flying, you press / to open the Internal Properties window. Go to /fdm/jsbsim/damage/ and then shift + click on the properties that you want to see on the screen.

@dany93 I've let your gear logic unchanged. It's just in JSBSim so that the behavior is more deterministic and relies less on luck :smile:

**Comment by onox** [comment]
@tigert I almost forget how to get the code. You can find it in branch bug-280.

**Comment by tigert** [comment]
Cool. Will try to test tonight if I have time. Better to offload the nasal stuff for better fps too I guess.

**Comment by dany93** [comment]
Bravo onox! :smile:
I had thought of this slowness of nasal compared with JSBSim xml (120 Hz), but I didn't know how to do. I'm only moderately used to these functions and external system xml files.
And the gear forces are truly quick to change.

However, I thought that the nasal worked at the *fps* rate, not these 0.25 sec polling (every 0.25 sec is very slow)

Can the lines 6 - 12 in physics.nas
`var get_gear_force = func (index, spring_coeff, damping_coeff) {`
 etc....
be deleted now?

**Comment by onox** [comment]
@tigert I have increased the required force. I have also added a check that the compression-ft is above a certain value otherwise I found that the gear could break without any visible bending. Now it will bend before it breaks.

I have also added (for the left and right gear) a second `<test>` block for the side force. The check for the side force used to be in the first `<test>` block together with the check for the main force, but putting those together is wrong, so I moved it to a separate block.

You can comment each whole `<test>` block by surrounding it with `<!-- -->` to disable it. That way you can focus on testing the main force and side force separately.

**Comment by onox** [comment]
> be deleted now?

@dany93 Thanks, I had forgotten about removing it.

**Comment by dany93** [comment]
My first tests (with the initial settings):
The nose wheel is much more sensitive to a bad landing, when you touch with the three wheels at the same time, or to a hard landing where it touches violently and too soon, or worst and obviously, if you touch with the nose wheel first. Seems very good.

The nose wheel breaking threshold (1400 lbs) is very limit at 2500 lbs gross-weight for a strong and long braking, but increasing slightly this threshold should be enough, without loosing this sensitivity to bad landing.

I have done a few 15 kts crosswind landings. Touchy but feasible.

This aircraft becomes (or will become) realistically difficult to land, differently from most of FG aircraft which are considerably too tolerant.

**Comment by dany93** [comment]
Second version (2400, 6500 lbs with compression criteria).
*(Only a few tests, to be confirmed)*

The nose gear is too hard to break, the main gear sometimes break before the nose on a "flat" landing.

I clearly prefer *without the compression test* for the nose gear.

Threshold force for the nose : 2000 lbs is enough, maybe a bit less seems possible.

But let's wait for tigert feelings.... And more tests from myself.

A nose gear is very fragile, a landing must be exclusively done on the main gear, the nose must be gently let to fall down. By retaining with the yoke.
Fortunately, I have never broken a nose wheel in RL, which makes that I have no experience.

**Comment by tigert** [comment]
Yeah, when you brake hard you really should pull back on the yoke to offload the weight from the nosegear. I think the main gear can survive such a hard landing that the belly touches the ground, like on that nasa video :-O

I am suffering from lack of time to actually test fly this, easier to help with comments, but I will try.

@wezzer , any luck with installing flightgear from git? :) maybe you can pitch in some testing too?

**Comment by wezzer** [comment]
I'd love to help you guys, but at the moment I don't have computer at home which I could use for FG. Pity.  @tigert , we could take a look on this at the aviation club.

**Comment by onox** [comment]
>I clearly prefer without the compression test for the nose gear. Otherwise we loose the improvement from the xml for the reactivity.

The compression test is so that the nose gear doesn't immediately change from "completely uncompressed (0.0)" to "broken". Have you tried `gear/unit[0]/compression-ft GT 0.2` or `gear/unit[0]/compression-ft GT 0.1`?

**Comment by onox** [comment]
Have you also tried 0.5 but with 1400 lbs force?

**Comment by onox** [comment]
IMO compression-ft 0.5 is ok, it's rather the required force is too high, so I suggest that I just revert the force back from 2400 lbs to 1400 lbs. Does that sound ok?

**Comment by dany93** [comment]
1400 lbs it too short, it is almost or attained on a strong braking.
I have tried 1500 lbs: still hard to break if I recall well (but I have tried many combinations, I can be wrong. The best is that I try it again).
The compression force is an artefact which hides a reality (**in FG**): the force exists and, like any force, it can break something even with a very small compression. The strong force at weak compression is due to a very quick displacement (compression velocity) via the damping factor: F = damping  x velocity. High velocity ==> strong force. If the damping is true (which can be discussed), this is true also IRL.
The only way to get rid of this would be to decrease the damping, the result would be a more quickly attained compression amplitude. Due to its shape (a piston) the nose gear is damped. Much less for the main gear. For the nose wheel, I do not know if there is really a shock absorber (which is usually asymmetric) or merely by the friction. In FG, the damping is symmetric, and making it asymmetric would complicate without changing the final point: whatever the damping, a "bad" landing on the nose gear must break it. Everything is in the definition (rather by feeling than by measure for us) of the bad landing which must break the nose gear.
>I have also added a check that the compression-ft is above a certain value otherwise I found that the gear could break without any visible bending

This is for the same reason as the nasal which doesn't work: the compression that you see is a 3D animation, which works at the fps rate. Much less slow than the FDM which detects the quick movements.

I hope being understandable, not easy to write and I do not wish to spend too much time to respond.

**Comment by onox** [comment]
I'll set it to 1500 lbs then for now.

**Comment by dany93** [comment]
I confirm.  With 1500 and compression 0.5 it breaks, but a bit hard to get it.
I like 2000 with no compression criteria. It breaks on a moderately bad landing but not on a good landing, main gear first to gently touch.

**Comment by tigert** [comment]
I guess the force is the one that counts and breaks the gear attachment structure? If you give a lot of force, you end up with full compression anyway, right? And you cannot really have a full compression without having a lot of force too (unless your pressure cylinder is empty, in which case there is no spring in the gear, but it still won't break until you have the force as well?

**Comment by dany93** [comment]
>I guess the force is the one that counts and breaks the gear attachment structure?

Yes.
Although the mechanical systems can hold a higher force before breaking when it is for a very short time. But this is not simulated in FG and I don't know in what extent it applies here. If we wanted to, the evaluation would be very difficult. Better trying to use correctly that we have.

> If you give a lot of force, you end up with full compression anyway, right? 

No. Or rather, it depends.
With a pure spring with no inertia, or for a long time, yes. You *"end up"*...
Here, we are with a damped system.The force is
`Force = Spring coefficient x compression + damping constant x compression velocity`
Due to the second term, you can *briefly* have a strong force with a small compression.

**Comment by wlbragg** [comment]
After reading this the the 1500 + 0.3 seemed to be harder to break that 2000 without, but maybe I didn't hit it right and need to test it more.
It still may be too easy at 1500 + 0.3. But I broke hard from touchdown to wheel stop and it didn't break, this was with little to no wind.
