### ISSUE TITLE
battery drain when alternator is off 

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#36]
XML15 - if an alternator is turned off (such by a failure), the battery should slowly drain all its energy over a certain period of time (minimally 30 minutes, probably more for a good working battery), causing a complete electrical failure. In case it was not a failure and the alternator is turned on again, the battery should recharge back over time

**Comment by Juanvvc** [comment]
Actually, this is already modelled but the battery has (IMHO) too much capacity.

**Comment by gilbertohasnofb** [comment]
By what I read, a battery minimal duration should be 30 minutes, but in reality it should last substantially longer. Do you know how much is the current capacity of the battery in minutes?

**Comment by Juanvvc** [comment]
According to my instructor, less than 5 minutes or you have to use external power. Probably, the battery on my C172 was not the best :)

**Comment by gilbertohasnofb** [comment]
Hmm, I don't know how different are these laws in different countries, but the FAA states that "In the event of a complete loss of the primary electrical power generating system, the battery must be capable of providing electrical power to those loads that are essential to continued safe flight and landing for [a]t least 30 minutes for airplanes that are certificated with a maximum altitude of 25,000 feet or less"

Source: http://rgl.faa.gov/Regulatory_and_Guidance_Library/rgFAR.nsf/0/B68CC9734E940D1F86257996006CB148

**Comment by Juanvvc** [comment]
Ok, I must clarify my comment :)

The electrical system that needs most power is the ignition system. Once the engine is running, you only have to feed a few instruments, lights and radio system. If the alternator fails and according to the FAA provisions, the battery should be able to keep runnin "those loads that are essential to continued safe flight". This means: switch COM2, ADF and DME off, transponder OFF, all lights OFF and consider switching COM1 off after the PANPAN message (if any) This way, you save your power for instruments and flaps for half an hour and probably more. On ground, switch all lights on and use the starter 2-3 times and your batteries will be empty in less than 5 minutes.

Hence, it is all about loads for the electrical system. Currently, loads were estimated by the original author:

- Battery: 12 A h, "ideal amps" 30A, 24V.
- Master breaker: accepts loads up to 55A (breaker implemented by us, but the limit is not checked yet)
- Starter: 12A (that means: engine could run for 1 hour using only electric power. Very unrealistic!)
- Main lights: 2-5A each (beacon, navigation, strobe, landing all together ~15A, or ~360W )
- Radios use 0.5A
- Other instruments use 1-2A

With everything ON and the engine running, the electrical system needs ~20A. With a battery of 12 A h, that means it lasts (with eveything switched ON) about 45 minutes. With ligths off, up to 3-4 hours. The starter could run for about 1 hour before depleting the battery. IMHO:

- The starter must use much more power. Probably, twice the current power consumption.
- The battery capacity should be reduced considerably, about a 25% of current capacity.

These calculations are fast calculations only to have an idea of the issue! They need to be reviewed throughoutly! I think we have an issue because of my understanding of the code, but I have not run a real test! Of course, the battery on my C172 was never empty so I cannot use any real experience here.

**Comment by gilbertohasnofb** [comment]
Thanks for the detailed reply, Juan! It does make complete sense to me now. 

> Of course, the battery on my C172 was never empty so I cannot use any real experience here.

I's likely that very few people will have experience with that, so probably we will need to make some informed (and maybe some uninformed) guesses.

**Comment by wlbragg** [comment]
"Starter: 12A (that means: engine could run for 1 hour using only electric power. Very unrealistic!)"
VS
"The starter could run for about 1 hour before depleting the battery. IMHO:"

Are you talking about cranking?
No battery I have ever seen could crank for even close to an hour. You must be talking about something else?
Did you mean alternator? 
If so, I am in agreement just by experience with car alternators that it could run for some time + or - 1 hour.

**Comment by Juanvvc** [comment]
Yes, I was talking about cranking.

Sorry if sometimes I'm not clear enough. During the day I'm constantly switching between three languages (Catalan, English, Spanish). I'm not a polyglot of any kind and my brain needs a time to adjust. At the end of the day I'm exhausted and I need a longer time to switch the language.

**Comment by onox** [comment]
So should we double the power consumption of the starter and reduce the battery capacity to 25 %?

**Comment by onox** [comment]
@Juanvvc So should we double the power consumption of the starter and reduce the battery capacity to 25 %?

**Comment by onox** [comment]
@tigert It seems @Juanvvc is currently at the beach, enjoying the sun :smile: Could you perhaps read this issue and answer my question about the starter and battery capacity?

Battery ideal volts is 24.0, amps is 30.0, and amp hours is 12.75.

**Comment by tigert** [comment]
I am not yet at the beach, so sure. :-)

The starter will burn the coils if you crank it for a long time, a lot before the battery will be empty. But the procedure is to reduce power consumption to minimum if there is alternator failure: turn of everything but essential navigation and communication to fly to the nearest airport. 

Basically when you lose your alternator, you turn off anything but the essential electronics. If you fly VFR on visual weather conditions and on uncontrolled airspace and to an uncontrolled airfield, I guess you could just turn continue to your destination without too much worry, as you could do the same trip with an aircraft without any electronics anyway - the engine is self-sustained and will work without battery. The situation is very different if you fly IFR in clouds and in contact with air traffic control and have to use radio navigation.

Anyway:
   * Battery will drain empty if alternator is dead and you have equipment using power
   * The time it takes to drain the battery depends on how much stuff you keep running
   * What should happen when you run out of battery? Basically the power will not just cut off, but should start to "brown out" and the voltage will drop, so the equipment should perhaps start to "dim" and maybe behaving somewhat erratically. Should this be modelled? Quite a lot of work for pretty specific situation of which there is not really much documentation of how things behave.

I guess the point is, the battery capacity can be anything from "horrible" to whatever the capacity is when brand new. And you could figure out power consumption of various avionics through googling, but for example with radios it depends a lot on how much you transmit [KX155 is 0.6A on receiving and 6A on transmit](http://www.bendixking.com/Products/Navigation-Communication/Glideslope-Receivers/KX-155A) according ot the website. We could of course model this but it would perhaps be a bit tricky to define how much is being transmitted and in practice you wouldnt really know too precisely when it will be empty anyway. In practice it might work if we model the battery like a fuel tank of a sort, and have some rough estimate for the "drain" of each piece of equipment and add them up and reduce the battery "contents" with equal drain.

http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf

The POH has procedures for electrical failure, but it's basically a "stuff will get worse, so land soon". How soon depends on how much your life depends on the electronic equipment.

**Comment by gilbertohasnofb** [comment]
Related to https://github.com/Juanvvc/c172p-detailed/issues/38
