### ISSUE TITLE
Some defaults are not properly set

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#383]
* Default livery was chosen to be 4X-CHV (wasn't properly changed in #300)
* Show occupants
* Enable complex procedures and damage (fixes @geoffmcl's issue in #376)
* Just like all the other switches and controls, make sure lighting is off as well

**Comment by gilbertohasnofb** [comment]
How can I test this, onox? When I loaded this branch in FG, I was shown a different livery and the damage was off, but this is probably because these things are saved between the sessions. So this also mean that just before the merge with fgdata, we have to double check that all these settings are where we want them to be because that's what people will get when they first start FG, right?

**Comment by onox** [comment]
If you are in your home directory:

```
cd .fgfs/aircraft-data
rm c172p.xml
```

**Comment by gilbertohasnofb** [comment]
Thanks, tested and merged.
