### ISSUE TITLE
FATAL:'-' found in propertyname after ''

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#450]
Following error occurs:

![687474703a2f2f7332382e706f7374696d672e6f72672f7970716167793162782f6a75616e7676635f30352e706e67](https://cloud.githubusercontent.com/assets/3361585/9607558/1d74724a-50ca-11e5-9552-b7ebd233e45f.png)

because of `<reference>-.75</reference>` in `Systems/ground-effects.xml`.

**Comment by gilbertohasnofb** [comment]
Is this the error that is troubling @thevirtualfer ?

**Comment by onox** [comment]
Yes, it's the error in https://github.com/Juanvvc/c172p-detailed/issues/6#issuecomment-135812981

**Comment by thevirtualfer** [comment]
Oh. Thanks @onox.

I don't realize i was filling #6 with this other issue.

There are two problems.

This one, and i don't understand why the rest of you are not getting this
issue, because it is a string check made on simgear/props.cxx

And, when i change the value to -0.75, the program generates a segmentation
fault in something like "doTrim" in JSBsim. i will check this with more
caution.

Any of you knows how to inform gdb where the source files are ?

I guess i need it to set breakpoints, etc.

2015-09-01 12:03 GMT-03:00 onox <notifications@github.com>:

**Comment by thevirtualfer** [comment]
@onox 

Is it possible that flightgear compiled with other version of libc ?

I tested the strtod() writing this code.

`#include <iostream>`
`#include <stdlib.h>`
`int main()`
`{`
`   char dvalue[] = "-.75" ;`
`   char *end ;`
`   double value ;`
` `
`   value = strtod(dvalue, &end) ;`
`   std::cout << "The value " << dvalue << " converted is : " << value << "\n" ;`
` `
`   return 0 ;`
`}`

The output is : 
> The value -.75 converted is : -0.75

**Comment by thevirtualfer** [comment]
Was the boost libs. Recompiled without boost and this issue is gone.

**Comment by onox** [comment]
You disabled boost!? I see many occurrances of `BOOST_FOREACH` in flighgear:

```sh
find . -type f -name "*.cxx" -exec grep -H "BOOST" {} \;
```

**Comment by thevirtualfer** [comment]
No, no, @onox.

The tutorial i followed, installs the last boost, the last OSG, etc. and tells flightgear to use those new version, instead what is installed on you machine.

What i do is compile only simgear and flighgear, and use what is currently installed. Not the last version.
