### ISSUE TITLE
reset aircraft state option

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#455]
After an user complain about the parking brake state being automatically saved between sessions, @ludomotico wrote: 

> [...] we need a "reset" command to cope with this situations, and a new option for the aircraft: save the previous state or reset the aircraft each time you start the simulator.

**Comment by wkitty42** [comment]
there was discussion way way way back about the parking brake... the consensus at that time was it was fine because supposedly folks started up in parking spots and followed the checklists... in my case, and the reason i brought it up, i start on the runway and then use autostart... if the brake isn't set, you start rolling when you throttle up... i prefer to throttle up, get to full power and then release the brake to launch down the runway...

i know that there's something in the sim that sets the defaults because no matter what i did to ensure everything was powered off at the end of a flight, the next time i loaded, some things would be turned back on before even running autostart... no clue if this was in the craft or in the sim but i suspect the sim because it is the same for every craft i've tested this one...

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> the consensus at that time was it was fine because supposedly folks started up in parking spots and followed the checklists

Well, the aim has always been to make the aircraft as realistic as possible. Surely you can fly using your own procedures, but it would be quite difficult to foresee all possibilities.

> if the brake isn't set, you start rolling when you throttle up.. i prefer to throttle up, get to full power and then release the brake to launch down the runway...

What you are describing is similar to a short field take off, and I think in RL you would use normal brakes and not parking brakes for that (though I may be completely wrong here). The point is that autostart is made for people who just want to enjoy the sim without too much headache about prodecures. If we manually set the parking brakes with autostart, then those folks will be wondering "why the plane isn't moving?". I think that if you want to use autostart AND use the procedure you described above, it's more than fair to apply parking brakes yourself if you judge it necessary :wink: 

> no matter what i did to ensure everything was powered off at the end of a flight, the next time i loaded, some things would be turned back on before even running autostart...

Which things?

**Comment by wkitty42** [comment]
@gilbertohasnofb most have been taken care of by specific code in the craft but as i recall, one only need to ensure that everything is off and the lights are dimmed... then exit the sim and start it up again... IIRC the key switch would be on and at least one or two other things but that was a while back when i last tested... might look again later but too late now...

**Comment by gilbertohasnofb** [comment]
> IIRC the key switch would be on and at least one or two other things but that was a while back when i last tested... might look again later but too late now...

I am having troubles with my installation of FG and I can't test it now either (today I plan to solve whatever problem is happening on my computer), but if you'd have the time to check those and report here it would be great, making this state saving consistent is fundamental IMO.

**Comment by wkitty42** [comment]
at this time, the items i've checked have been properly off when i've specifically turned them off and exited the sim via the esc/exit button in the sim... i run full screen so using the 'x' is not available ;)

**Comment by gilbertohasnofb** [comment]
Cool, so whatever problems we had should be solved now, thanks for testing it!

**Comment by wkitty42** [comment]
i forgot to clarify that i tested with the craft as released in FGDATA... i'm running FG 3.7 from GIT... i haven't updated my local copy of the craft from this repo in a while... i've been waiting on the retopo to complete...

**Comment by gilbertohasnofb** [comment]
Hmm, I am thinking about the quote by @Juanvvc above:

> we need a "reset" command to cope with this situations, and a new option for the aircraft: save the previous state or reset the aircraft each time you start the simulator.

Isn't this exactly what we currently have? If the save state toggle is checked, then the aircraft will save its state, else the aircraft will be reset to a reasonable state (parking brakes on, switches off, etc.). I just don't understand what this issue is about any more...

**Comment by wkitty42** [comment]
i think it has actually be completed by adding the state saving code as well as resetting everything to the saved state on start regardless of what the sim was doing... eg: if the sim was forcing the key switch to be on, we now force it off...

however, this also brings up something that i've been forgetting to mention... there was a bit of talk in the dev list about if certain things should be changed like the sim forcing the key switch on all the time... i made the comment that the c172p members should be involved in the discussion since it is the "leading craft"... @zakalawe (james turner) agreed...

i don't know how often @onox, @gilbertohasnofb, or @wlbragg or others read the dev list but i left a large opening right there for someone with more knowledge of what, exactly, we're having to override... the idea being that they would step in and discuss these forced settings and how to handle them... removing their forced setting from the sim on start up would reduce some of our code and ""tricks"" so that we would not have to specifically force the battery, alternator, avionics, strobe lights and key switch off every time... at least those five items, as i recall...

i may have gotten lucky figuring out gmane's web interface... here's a link to the original post, my response and james back to me...

original post by @zakalawe  http://permalink.gmane.org/gmane.games.flightgear.devel/79567
reply post by me http://permalink.gmane.org/gmane.games.flightgear.devel/79568
reply to my reply by @zakalawe  http://permalink.gmane.org/gmane.games.flightgear.devel/79574

**Comment by gilbertohasnofb** [comment]
> i think it has actually be completed by adding the state saving code as well as resetting everything to the saved state on start regardless of what the sim was doing... 

Great, so I will reference it to that PR and close this issue

>  don't know how often @onox, @gilbertohasnofb, or @wlbragg or others read the dev list 

Well, I go through it daily but given the amount of FG projects I am involved with, I really just scroll it quickly to see if something is interesting or does concern me. But I probably miss interesting posts very often...

> there was a bit of talk in the dev list about if certain things should be changed like the sim forcing the key switch on all the time... i made the comment that the c172p members should be involved in the discussion

Hmm, I read these links you sent but I don't think I am the right person to reply to this kind of thing (as I know nothing of what would be the consequences of those propositions and so I have no opinion about it). Maybe @onox could have a look at it.

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/518

**Comment by wkitty42** [comment]
yep, i was thinking about @onox for that, too :wink:

**Comment by zakalawe** [comment]
> On 11 Dec 2015, at 12:50, waldo kitty <notifications@github.com> wrote:
> 
> yep, i was thinking about @onox for that, too 

I would be grateful if someone could (on the dev list) for sure!

Kind regards,
James
