### ISSUE TITLE
Cabin temperature gui.popup too often

### ISSUE THREAD

**Issue by TeXnicer** [Juanvvc/c172p-detailed#462]
When having cabin temperature either below 0°C or above 32°C a gui.popup-message (guess what?!) pops up. But this continously, so this blocks other simulation occurences, e.g. throttle percentage or even cabin air/cabin heat readout. This makes adjustments very difficult, especially in order to react on that specific message.

**Comment by onox** [comment]
The logic in `Nasal/weather.nas` could be tweaked a bit.

**Comment by wlbragg** [comment]
Yeah I agree that it can be annoying to have that message, to bad we can't feel when it gets warm or cold in the sim.

Maybe we could have it
>only display the popup tip only once in a while

I also thought maybe when it prompted you about the temp, we could have it give you an option to "have pilot automatically adjust temperature to a comfortable level" or something, even the option to shut it off at that point.

The fog and ice logic probably is fairly aggressive, especially ice. I think the conditions to allow for same are fairly modeled. But once conditions are favorable for the creation of fog or ice, it may need to be slower developing from that point forward, especially for ice. However. I have seen fog come on quite quickly under the right conditions.

**Comment by tigert** [comment]
It's also sometimes hard when ypu have summer and warm and humid, you have this dilemma of either fogged up or too hot cockpit. I guess the logic how it works might have some issues. Now when it is autumn, temperatures are low enough that using heater doesnt make cabin too warm.

**Comment by wlbragg** [comment]
For anyone following this issue. I added the ability (in-sim GUI) to adjust the factors that control how fast or slow the fog and ice is created and how fast or slow the heat and air can handle the event.

Please test it and see if you can get some meaningful values in place to control this system.

Until it is merged it is in heat-air-refactor branch.

**Comment by onox** [comment]
I don't think this GUI should be added. You can decide though whether to expose the factors to the property tree:

1. Read the factors somewhere at the top of the `weather_effects_loop` function.

2. Read `frostlevel` (`/environment/aircraft-effects/frost-level`) and `foglevel` (`/environment/aircraft-effects/fog-level`) also near the top of that function. Currently they are at the top of the file instead. As you can see in the file (`Nasal/weather.nas`), the values of frostlevel and foglevel are written to the property tree, but they aren't read from it.

3. Fix `moisture` as well. I think it's the only Nasal-only variable currently.

Also, I'm not sure about the `if (!getprop("/fdm/jsbsim/weather"))` check in the code. I think the levels should always be computed, and instead put the check in the model XML files somewhere in an appropriate place. I'm not sure whether that is possible, maybe we need an extra function (filter) that toggles between the actual level and 0.

This way you just hide the frost and fog, instead of completely setting its state to 0.

**Comment by wlbragg** [comment]
@onox, I guess numbers 1-3 are "if" I decide to expose everything?

I'm not interested, I guess?

What I exposed already is just the factors (speed) of all the elements of frost and fog formation and the only reason I exposed them was to make it easier for those that wanted to try to adjust the physics of this system.
Because this is now a side branch for debug purposes only I think the only thing I am left with here is
>I'm not sure about the if (!getprop("/fdm/jsbsim/weather")) check in the code

I see where your going with this but I think we're good as is. Everything is still being calculated, we just shut off the final step of feeding the info to the frost and fog switches. In fact, if you were not into fog formation and shut off the "Frost and Fog" then subsequently enter into the correct conditions and turned it back on it would be at the same formation level as if you never turned it off.

So I think were done here other than the the initial complaint about
>Cabin temperature gui.popup too often

Which brings us back to, 
1) adjusting the factors (which will make the temperature rise/fall slower, which in my opinion needs to be done). and/or 
2) adjusting the timer on the popup warning (also in my opinion may need to be done).

The tool is now available to make the first choice easier. Let leave the branch as a separate debug tool. In fact, I think if we leave it available for a while, we could remove all the commented out debug lines from master's weather.nas and leave it in the debug branch.

**Comment by wlbragg** [comment]
I have an idea, even though the default heat and air flow on the RL c172 does not have climate control as in picking a temperature and the system keeps it at that temperature. What it does have is a human to feel the temp and then adjust the sliders. We can't feel it in the sim.
So, I think we should have a check box, something to the effect, "Maintain comfortable air temperature".
How I will program it is to use a range, say from 65-75 deg (18.3-23.8c) and just keep adjusting the slider to stay in that range. Probably including the slider animation. That way it is simulating the occupants feeling the temperature and constantly adjusting the sliders.

Do that sound like a reasonable thing to do?
If so, I need a shorter name for the GUI check box choice.

**Comment by onox** [comment]
Sounds like a good idea, but shouldn't we first improve `Nasal/weather.nas`? I'm thinking about converting it to maybe a JSBsim system.

**Comment by gilbertohasnofb** [comment]
@wlbragg So in that case, that would be equivalent as disabling the fog and frost effect, as your code would automatically take care of it, and so the only difference would be that the levers would automatically move instead of staying still. If you think that's worth it, you can of course go for it, but then I'd suggest we remove the "disable frost/fog effect" and substitute it for the new "automatically control cabin temperature". What do you think?

**Comment by wlbragg** [comment]
>I'm thinking about converting it to maybe a JSBsim system.

OK, I think I can do that too while I am at it.

>I'd suggest we remove the "disable frost/fog effect" and substitute it for the new "automatically control cabin temperature"

Even better, then we don't have to add another GUI choice.

**Comment by tigert** [comment]
i think the frost stuff is a nice piece of realism. The popup is kinda annoying (on hot summer the temp can be over 32C no matter what you do with the sliders :-) yet it is not really a big problem, maybe just time for shorts and tshirt and more airflow :)

**Comment by tigert** [comment]
The frost can be turned off, so it is not in the way if you just want to fly. I think this is important in the default aircraft, if you are just learning, it is nice if you do not have to handle too much at once, yet we can implement a lot of stuff like that as long as it is not a problem for learning basic flight technique first. Realism can be added gradually as the pilot learns -just like in real life when the instructor lets you handle gradually more tasks as you progress..

**Comment by onox** [comment]
> OK, I think I can do that too while I am at it.

Can I do this? I'm already working on it :smile:

**Comment by wlbragg** [comment]
Absolutely!

**Comment by onox** [comment]
Btw, do we want the air movement + heating to be dependent on the electrical system? Any circuit breaker we should depend on?

**Comment by wlbragg** [comment]
FYI:
To put it simply, 

The existing code heats the air temp at a different rate than the surface temp.
The air flow is independent from the heat flow.
Heat flow introduces heat into the airflow.
Fog is dependent on moisture on surfaces which id dependent on dewpoint which is dependent on air temp.
Ice is dependent on "moisture on surfaces" and internal surface temperatures.

**Comment by wlbragg** [comment]
Probably not because it is a mechanical slider that introduces the heat and air.

**Comment by wlbragg** [comment]
And the heat should work by simply passing air over the heat coil that has water or fluid moving through it. Unless an aircraft uses a different system to capture heat off the engine.

**Comment by onox** [comment]
But what controls the heat coil then? :smile:

**Comment by wlbragg** [comment]
>But what controls the heat coil then?

I'm not sure anything does, the airflow flap that the slider controls allows more or less air over the heat coil, introducing more or less heat into the air flow.

If anything it might have a thermostat, but I don't see why it would need it, unless it is inline with the rest of the coolant system that uses the thermostat.

I'm guessing at this is as much as I know how automobiles work, it may be different for aircraft.

**Comment by onox** [comment]
Yes, but the heat coil isn't heated automatically by itself, right? Unless it's made from plutonium or something :laughing:

**Comment by wlbragg** [comment]
>on hot summer the temp can be over 32C no matter what you do with the sliders :-)

That would be the correct behavior without "air conditioning" , they do make an after market air conditioning for small aircraft.

**Comment by wlbragg** [comment]
> heat coil isn't heated automatically

OK it requires the engine heat which requires it running, OK I see your point!

**Comment by onox** [comment]
Hehe :smile:

**Comment by wlbragg** [comment]
Microwaves from the sun! :sunny:

**Comment by onox** [comment]
And the `heat-coil-temp-degc` is then simply a function of what exactly? (egt, oil, etc.?)

**Comment by wlbragg** [comment]
Don't know. I can search for it.

**Comment by wlbragg** [comment]
>most single-engine aircraft that use a heat muff around the engine exhaust,

**Comment by onox** [comment]
So we could use `/engines/active-engine/egt-norm` in that case?

**Comment by wlbragg** [comment]
What is egt-norm?

**Comment by wlbragg** [comment]
time?

**Comment by onox** [comment]
Exhaust Gas Temperature (normalized -- between 0 and 1)

**Comment by wlbragg** [comment]
In a loose connection, I guess, I'm still trying to see exactly what a heat muff is?

**Comment by onox** [comment]
OK, I can wait, for now the heat slider does not depend on the engine.

**Comment by wlbragg** [comment]
So this heat muff is just transferred engine radiation heat?

**Comment by onox** [comment]
Uhh... I guess so? You told me about a "heat coil" :smiley:

**Comment by wlbragg** [comment]
Well this is more like what I figured and you can see it these are tied into the systems.
>Consider these two items.  Exhaust gas temps are around 1400 degrees ! !   Oil temps are around 350 degrees. Which would you rather use ?   Drawbacks :  If you get an oil leak, you could loose your engine ! !   If you get an exhaust leak, (in the exchanger) you could get carbon  monoxide poisoning. 

Let me see what this "heat muff" is and if it is for sure what the 172 uses.

**Comment by wlbragg** [comment]
The above was in reference to getting more heat into the aircraft cockpit.

**Comment by wlbragg** [comment]
OK,

>The 172s heater uses heat from the exhaust gas manifold to heat up air which enters the cabin.

**Comment by wlbragg** [comment]
That should answer what we need.

**Comment by onox** [comment]
OK.

**Comment by onox** [comment]
The JSBsim implementation is basically complete, but I'm noticing that `/environment/relative-humidity` quickly goes to 100 when I'm above, lets say, 1000 or 2000 ft. At FHAW.

**Comment by wlbragg** [comment]
I used /environment/dewpoint-degc. I remember the relative-humidity seemed wrong or broken.

**Comment by wlbragg** [comment]
Also, relative-humidity is basically the measurement of the amount of water in the air, dew-point is at what temperature that water condenses into liquid.

**Comment by wlbragg** [comment]
Not official weather related statements but more my basic understanding.

**Comment by wlbragg** [comment]
In case you didn't already know this, the fog or moisture on the glass, in my implementation, would only happen when the dew-point temp reached or exceeded the air temp. 

I guess the official explanation is
>Dewpoint is related to the quantity of moisture in the air while relative humidity is related to how close the air is to saturation.

**Comment by wlbragg** [comment]
So my explanation wasn't quite accurate.
However,
>Dewpoint is related to the quantity of moisture in the air

I think is a poor description as it is dewpoint-temp that we are talking about, and that is the temperature at which dew will form, related to amount of water in the air, yes.

Here in KS, in the spring, I have observed that the down pours of a thunderstorm let go when the air temp drops to the dewpoint temp in the afternoon. How much of a down pour I think does have to do with the dewpoint also because you can have 100% relative humidity and no rain.

**Comment by onox** [comment]
Never mind it's just FHAW.

**Comment by onox** [comment]
> dew-point temp reached or exceeded the air temp

Dew point cannot exceed air temp, because you cannot get more than 100 % relative humidity :wink:

**Comment by onox** [comment]
I calculated the dew point using the cabin temperature. I'm guessing `/environment/dewpoint-degc` uses `/environment/temperature-degc`.

**Comment by wlbragg** [comment]
I don't think that is a correct statement. Yes, you can't exceed 100% relative humidity. But RH is the saturation of the air. Dewpoint is the temp at which that saturated air condenses into liquid.

**Comment by onox** [comment]
Btw, shouldn't we always enable frost when temp gets below 0? The old Nasal implementation depends on the `moisture` variable, which depends on surface temperature and cabin air dew point.

**Comment by wlbragg** [comment]
No, you can't get frost without dew.

**Comment by wlbragg** [comment]
What is your dewpoint calculation?

**Comment by onox** [comment]
> Dewpoint is the temp at which that saturated air condenses into liquid.

If RH = 100% then dew point = air temperature

**Comment by wlbragg** [comment]
No, that is not right.

**Comment by wlbragg** [comment]
What I mean by "that saturated air", isn't 100% saturated. It can be only 50% sat and still get dew if the dewpoint reaches or exceeds the air temp.

**Comment by wlbragg** [comment]
Td = T - ((100 - RH)/5.)

**Comment by wlbragg** [comment]
That is  a dewpoint temp calculation.

**Comment by onox** [comment]
I'm using the Arden Buck equation. But calculating the dew point is not the problem.

**Comment by wlbragg** [comment]
Note the (100-RH)

**Comment by onox** [comment]
Yes, thus RH <= 100

**Comment by onox** [comment]
If RH = 100 then Td = T

**Comment by wlbragg** [comment]
No, I don't think that is correct. You can get 100% RH and not have dt - t.

**Comment by onox** [comment]
Anyway, what if the dew point is -37 degree celsius and surface temperature -33. Then surface temperature is greater than dew point, so you dont' get dew. But you don't get frost either? At -33 deg celsius?

**Comment by wlbragg** [comment]
OK, that does seem to be the formula, how are you applying it.

**Comment by wlbragg** [comment]
I keep missing your posts or they are changing over time?

>But you don't get frost either? At -33 deg celsius?

I don't see that as wrong. Just because it is below 0 does not mean you will get frost. You have to have the moisture and the dewpoint is still the dictator at which temp the moisture in the air turns to dew.
Maybe there are other factors that I am unaware of.

**Comment by wlbragg** [comment]
I guess we would really need to research this or have a weatherman formulate it for us to be sure. I have to admit I am guessing at some of this strictly based on what I think I know (which has been wrong many times before). But I really don't think that temp alone should be the factor of frost. That doesn't make sense to me.

**Comment by wlbragg** [comment]
As far as calculating the dewpoint from the internal air temp VS the external temp calc of dewpoint that is already available, in reality, where is this dew forming? I'd venture to say it is both interior and exterior. I would have to put some thought to that to have anything meaningful to add.
It is obviously a very complicated event in reality that we are trying to simulate in FG.

**Comment by wlbragg** [comment]
>Contrary to common opinion, frost is not frozen dew. Frost is a crystalline formation of small, thin ice crystals that form on objects when the air directly above the object reaches the frost point. The frost point is the temperature at which air can no longer hold its water in vapor state, and the air temperature reads close to or below freezing (32 degrees Fahrenheit). Frost formation greatly depends on the level of relative humidity in the air. Frost forms when the dew point reaches freezing point or lower and the air temperature equals or is less than the dew point temperature. When this happens, the dew point equals the frost point.

Read more : http://www.ehow.com/how_5909936_calculate-frost-point.html

**Comment by wlbragg** [comment]
Like I said, a lot of guessing on my part. :smile\

**Comment by wlbragg** [comment]
>air temperature equals or is less than the dew point temperature

So the dew point can be greater than the air temp, for what it's worth.

Later!

**Comment by tigert** [comment]
Wow lots of discussion. It is not even that sophisticated. The system is very archaic. 

The operating handbook has actually a quite good explanation of the logic and function of the aircraft systems: http://www.aerodynamicaviation.com/documents/cessna-172p-1982-poh.pdf see page 7-31.

Basically there are two things:
  * Overhead vents (the round tubes on the top corners of the windshield and on the ceiling above the back side windows take their air from the wing leading edge holes. This is always cold air, and the vents just blow in air from the aircraft slipstream when you open the vents. The front vents close when you push them fully in, if you pull them outward from their tubes (it's a tube inside a tube kind of thing) a small hole in the side of the tube passes air into the cabin. Like here: http://pilotbrian.blogspot.fi/2009/10/ventubes-replacement-air-vent.html

  * The "heater" air vents. These consist of two defrost outlets for the windshield on top of the glareshield, an air outlet in front cabin floor in front under the instrument panel I think, and two outlets for the back seat. I *think* these are in the floor, but I don't remember exactly, we'd need to look for clues in some photos of the interior :-) 

In any case, the ceiling vents are just cold air blowing from the wing leading edge, and they flow when the propeller or airspeed creates airflow at the wing root. No blower fan except the propeller :-)

The same applies to the heater. There is no fan, it just has a small "door" on the right side of the fuselage:
http://www.kentstreetshs.wa.edu.au/Images/General/cessna%20172SP.jpg - this is directly opened and closed via cable when you pull the "CABIN AIR" lever. So this lets cold air in.

The warm air comes from the same "box" around the exhaust pipe that feeds the "carburettor heat" air: There basically is a small metal "muff" around the exhaust pipe, the pipe gets hot when the engine runs, and it heats the air passing through the muff. This is fed from the engine air intake under the front nose of the cowling. 

These two air streams (warm from the carb heat muff, cold from the "side door") are then mixed with the "cabin air" and "cabin heat" levers.

So if I recall correctly, it works like the old fashioned two-sided water sink: you twist the "hot" knob to get hot water and cold knob to get cold water, and adjust the amounts to get the temperature and flow that you wish.

Completely mechanical. :-)

**Comment by tigert** [comment]
Also, when you calculate the frost point, you need to consider that the air humidity is significantly different inside the cabin compared to the weather engine, because people's exhaled breath is very moist. This does play a significant role, just like in a car on a cold, clear winter day: You can have a completely clear cabin windows when you start up and get folks in, but things fog and frost up quickly when everyone breaths in side the car, while the window surfaces and the whole cabin is very cold still.

**Comment by onox** [comment]
Currently the air humidity from outside is used. So it should be multiplied with some factor depending on how many people there are in the cockpit?

**Comment by wlbragg** [comment]
Yes I suppose the number of human on the inside. It does play a big roll (initially) in the amount of fog that can be produced.

**Comment by wkitty42** [comment]
plus their body heat contributes to warming the cabin and providing some defrosting heat after a bit... that'll turn interior frost into moisture on the windows if the windows are cool enough...

**Comment by tigert** [comment]
Yeah, it's a complex state machine. :-)

Also, the air mixture changes when you start engine, open doors or windows, or are in motion, as then there is new air flowing into the cabin. In practice when the air flows, the fog will clear fairly quickly. For the ice to melt, the cabin needs to warm up to heat the plastic windows as well, at which point the ice melts.

The issue I had before is that it used to fog up the windows on moist summer weather and adding heat worked, but then I got constang nagging of the "cabin temperature" popup because the heater warmed the cabin too much. In practice I think the biggest contributing factor to defogging is the airflow, as it's already reasonably warm on summer days. On winter you need the heater to keep the windows clean, because if the cabin is very cold, the windows are so cold the breathed moisture freezes into them, and the cabin air alone is not enough.

So maybe it should be so that it takes the indoors people into account, more so when engine is stopped and the aircraft sits still) - since then folks breath moisture inside, but it does not move out. Winter on the other hand might work when you consider that moisture from breath freezes on sub-zero (celsius) windows, so to clear it you need heat. We keep our club aircraft on constant heater using conventional car interior heaters (Defa or whatever brands there might be) for the cabin - since avionics like to stay warm, as in cold temperature the moisture goes into the electronics as well..

**Comment by onox** [comment]
> These two air streams (warm from the carb heat muff, cold from the "side door") are then mixed with the "cabin air" and "cabin heat" levers.

Ah, I thought that the cabin air lever controlled how much air you would get from the air intake and the cabin heat level would then divert some of the air to the engine muffler.

**Comment by onox** [comment]
* Support cold air from overhead vents (amount depends on how much they are pulled outward + airspeed (IAS) and propeller RPM)
* Make the air from the air duct (controlled by cabin air slider) also depend on airspeed (+ propeller RPM as well?)
* Separate air flow of heat (air intake) and cold air (side door)
* Support cold air when a door or window is open
* Adjust relative humidity using the number of humans in the cabin
* Adjust cabin air temp using number of humans in the cabin

**Comment by wlbragg** [comment]
See #576 and #582
