### ISSUE TITLE
Fuel quantity state could be saved between sessions

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#503]
Fuel quantity state could be saved between sessions if the user activates it via a toggle in the aircraft menu (default = off, to avoid creating problems for people who "just want to fly").

**Comment by gilbertohasnofb** [comment]
@onox if you and all others think this is a good idea, I volunteer to implement this

**Comment by wlbragg** [comment]
I think it is a good idea, we save time, were going to save oil state, I think fuel is appropriate.

**Comment by gilbertohasnofb** [comment]
I agree, this will force those who want a very realistic simulation to check for fuel before every flightf. I will work on this then.

**Comment by gilbertohasnofb** [comment]
Hmm, this is a tricky one because I can't simply save the state of the fuel (since people who "just want to fly" would then crash and never be able to take off again due to lack of fuel). But then again, I can't just have a toggle disabling fuel consumption. So basically I think we need this:

- save the fuel level in ANY situation
- add a master toggle in the aircraft menu: `[ ] save fuel quantity state between sessions`
- if ticked, then once the sim is loaded we refill the tanks. If not ticked, the tanks remain the same level

What do you think, @onox? And how can I implement this using only XML? `<logic>` is always evaluated, so is there a way of checking a conditional _only_ when the sim loads up?

**Comment by gilbertohasnofb** [comment]
A hack-ish solution: using a `<logic>` which contains a condition "if the FDM is not initialized", so it will evaluate the code just before the aircraft is fully loaded in the sim. But this sounds horribly inelegant...

Else I could also make a Nasal function that is called just once when the FDM is initialized.

What you think?

**Comment by wlbragg** [comment]
>f save-fuel is false, then once the sim is loaded we refill the tanks. If true, then the tanks remain the same level

I think this works!

**Comment by wlbragg** [comment]
It is a simple solution requiring one property, a save state and one line of nasal c172p loop that checks the save fuel property on fdm init.

**Comment by gilbertohasnofb** [comment]
Okay, I will work on that right now :+1:

**Comment by wkitty42** [comment]
On 11/04/2015 05:05 PM, Gilberto Agostinho wrote:
> Hmm, this is a tricky one because I can't simply save the state of the fuel
> (since people who "just want to fly" would then crash and never be able to take
> off again due to lack of fuel). But then again, I can't just have a toggle
> disabling fuel consumption. So basically I think we need this:
>
>   * save the fuel level in ANY situation
>   * add a master toggle in the aircraft menu: |[ ] save fuel quantity state
>     between sessions|
>   * if ticked, then once the sim is loaded we refill the tanks. If not ticked,
>     the tanks remain the same level
>
> What do you think, @onox <https://github.com/onox>? And how can I implement this
> using only XML? |<logic>| is always evaluated, so is there a way of checking a
> conditional /only/ when the sim loads up?


ummm... wait... have you guys forgotten about

   --enable-fuel-freeze

??

that will freeze the fuel flow and keep it at the same level all the time... 
i've flown around the world in the c172p without ever landing because of this 
option... let's not over think things, eh? ;)

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> ummm... wait... have you guys forgotten about --enable-fuel-freeze

I don't think you understand what I am doing here at all. I wrote before that I didn't __want__ to implement a fuel freeze, and that I think that fuel should be consumed regardless of the fuel level state being saved between sessions or not -- and that's what I implemented. It's the user's business if he wants to disable fuel consumption.

**Comment by wkitty42** [comment]
On 11/05/2015 06:21 AM, Gilberto Agostinho wrote:
> @wkitty42
>
>     ummm... wait... have you guys forgotten about --enable-fuel-freeze
>
> I don't think you understand what I am doing here at all.

you may be right...

> I wrote before that I didn't *want* to implement a fuel freeze,

i wrote what i did because *no one* needs to implement a fuel freeze in nasal or 
xml or whatever because it is already available in the sim and bypasses all of 
that stuff :smile_cat:

> and that I think that fuel should be consumed regardless of the fuel level
> state being saved between sessions or not

i think i can agree with that... i'm curious to see how it works with the sim's 
built-in fuel freeze capability... remember that there was a problem back before 
the FDM was converted to XML where i was unable to get up to altitude and that 
was due to (IIRC) my using the fuel freeze and the nasal code not handling it 
properly in that the mixture changes weren't being recognized... fixing that was 
one of my earliest offerings but it was ""shot down"" because of the new XML 
rewrite of the FDM which was a really huge GoodThing<tm> :)

> -- and that's what I implemented. It's the user's business if he wants to
> disable fuel consumption.

agreed and no problem there :+1:
