### ISSUE TITLE
3D modeller for hire!

### ISSUE THREAD

**Issue by legoboyvdlp** [Juanvvc/c172p-detailed#632]
Hello!
In January I would like a new challenge...
I just got Blender.
I can't really think of anything to make.
So, I guess, could you think of an instrument you'd like modelled?

Disclaimer: I don't know the least thing about Blender.

**Comment by gilbertohasnofb** [comment]
Hi @legoboyvdlp, since what you wrote is not an "issue" I will close it, ok? We use these issues only to create bug reports or enhancement proposals AFAIK. About working on a 3D issue, have a look on our list of things to be done: https://github.com/Juanvvc/c172p-detailed/labels/3D%20model

Maybe you can start with something simple (at least it looks simple to a Blender illiterate like me): https://github.com/Juanvvc/c172p-detailed/issues/418

Cheers.
