### ISSUE TITLE
Wrong LED segments in DME instrument

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#707]
Some of the numbers (1, 3, 4, and possibly 8 too) are displayed incorrectly:

1 is displayed on the left side, 3 is displayed as E, 4 as h.

Example:

![fgfs-screen-478](https://cloud.githubusercontent.com/assets/3361585/12946848/acb6b9d4-cff7-11e5-9643-50e7fefdc250.png)

@gilbertohasnofb Is this a UV mapping or texture thing?

**Comment by gilbertohasnofb** [comment]
It's a UV-map problem, see the texture file:

![ki266](https://cloud.githubusercontent.com/assets/5700795/12946942/409606fa-cff8-11e5-8210-e1777b931375.png)

**Comment by gilbertohasnofb** [comment]
It's not just some of the numbers, but some of the digit displays that are inverted (the thing is that we can't tell with certain numbers because they are either symmetrical when upside down (e.g. 1, 8) or look like another number (6 and 9, 2 and 5).

There are six digits in the display, the problematic are: the first and third, then fourth and fifth:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/12947251/59840070-cffa-11e5-8f9a-e52d01d0bf99.png)

**Comment by onox** [comment]
Ah, then it looks like 1, 3, 4 are inverted.

**Comment by gilbertohasnofb** [comment]
I updated my comment above, I think the 1st , 3rd and 5th digits are problematic. The 4th may also be, but I am not sure...

**Comment by wlbragg** [comment]
For some reason this entire model, both parts dme and ki266, were full of these problems. I originally notice several mirroring problems on the dme side, then noticed them o the ki266 side. I'm not clear how to solve this, you can't see the trouble in blender because I would imagine this is a textranslate animation of some kind?
I think this is a good argument for working from a blend file and not the ac. The had no blends and required importing the ac, maybe that is what set all this in motion. I didn't do anything that would have caused these texture issues except import the ac's.

**Comment by gilbertohasnofb** [comment]
@wlbragg since we now have the blend files, I propose you try inverting the only those three digits I mentioned before upside down (1st, 3rd and 5th). I can then test it in the sim.

**Comment by wlbragg** [comment]
OK

**Comment by gilbertohasnofb** [comment]
I believe the objects in Blender that need to be flip are:

- `Left.1`
- `Left.100`
- `Right.10`

**Comment by gilbertohasnofb** [comment]
After we test and see if there is anything else that needs to be changed again.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
Wow, if you look really close at the 0's in the ki266.blend file, you can see the three you mentioned are slightly shifted down below the others (mirrored incorrectly) when looking at them in texture mode. So I am pretty sure you got this right @gilbertohasnofb.

**Comment by gilbertohasnofb** [comment]
That's good news, then! I think we will be confident to declare this issue solved (I started to get so neurotic with this damn DME after so many things went unnoticed by we all!)

**Comment by wlbragg** [comment]
:scream:

**Comment by gilbertohasnofb** [comment]
Totally!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/708
