### ISSUE TITLE
ASI instrument still functioning with pitot tube cover

### ISSUE THREAD

**Issue by onox** [Juanvvc/c172p-detailed#710]
ASI instrument still works with pitot tube cover visible.

As a quick fix we should set it to 0. Better behavior will be implemented in #538.

**Comment by gilbertohasnofb** [comment]
Do you know what introduced this error? The only thing I changed on AI.xml in those instrument commits was the rgb -> png conversion (since there is a declaration of textures in that xml file), see: https://github.com/Juanvvc/c172p-detailed/commit/1f9a5914ae8654675baf2c5b65942f9dd2272082#diff-423842a6758bb86a1de1c0524ed67071

The logic of the pitot tube cover is done in https://github.com/Juanvvc/c172p-detailed/commits/master/Systems/ground-effects.xml

**Comment by gilbertohasnofb** [comment]
Could it be that the property `instrumentation/airspeed-indicator/serviceable` is broken in FG 2016.1.0? Or maybe it's related to this addition here? https://github.com/Juanvvc/c172p-detailed/blob/master/Systems/indicated-airspeed.xml

**Comment by onox** [comment]
> Or maybe it's related to this addition here? https://github.com/Juanvvc/c172p-detailed/blob/master/Systems/indicated-airspeed.xml

Yeah.

**Comment by onox** [comment]
I'll create a fix.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
@gilbertohasnofb See the PR above. Could you please test it?

**Comment by gilbertohasnofb** [comment]
Sure!

**Comment by wlbragg** [comment]
I'm concerned about the regression of the pitot cover, I hope it isn't more extensive.
