### ISSUE TITLE
exterior rain effect shouldn't be applied to the bottom wing

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#738]
As reported by @wkitty42, the exterior rain effect shouldn't be applied to the bottom wing. Haven't tested this myself as for some reason I am not getting exterior rain (only windshield raindrops).

**Comment by wlbragg** [comment]
If I remember correctly, there may not be anything we can do about this. I'm pretty sure that the shader won't account for when it should be applied to the object by any of the objects positioning or angles. If that is the case, and I think it is, our only option would be to break the wing into two objects, an upper and lower, and apply the effect to the upper object only. The effect is so subtle I really don't think it's worth the effort.

**Comment by wlbragg** [comment]
>Haven't tested this myself as for some reason I am not getting exterior rain (only windshield raindrops).

Nether am I, it's a fgdata or core issue. I'm using 2016.2.0 and current fgdata. I sure hope whoever broke it reverts whatever commit did it and doesn't leave it like that for a couple versions (like the particles)!

**Comment by gilbertohasnofb** [comment]
>  to break the wing into two objects, an upper and lower, and apply the effect to the upper object only

Yeah, that crossed my mind as well. 

> Nether am I, it's a fgdata or core issue

So let's leave this issue opened and we think about how tackling it (and if we would do it) later, is that all right?

**Comment by wlbragg** [comment]
:+1:

**Comment by gilbertohasnofb** [comment]
I just tried reproducing this but I can't see _any_ rain effect on the fuselage/wings, just on the windows. Did something change concerning this effect?

**Comment by wkitty42** [comment]
On 08/07/2016 08:09 AM, Gilberto Agostinho wrote:
> I just tried reproducing this but I can't see /any/ rain effect on the
> fuselage/wings, just on the windows. Did something change concerning this
> effect?


i'm not seeing the rain drops' splashes on the underside of the wing any more, 
either...

**Comment by gilbertohasnofb** [comment]
@wkitty42 but do you see them in the top side, or anywhere else in the fuselage? This is the thing: I don't think this issue is fixed, I think the effect got broken somehow!

**Comment by wkitty42** [comment]
On 08/07/2016 09:47 AM, Gilberto Agostinho wrote:
> @wkitty42 but do you see them in the top side, or anywhere else in the
> fuselage? This is the thing: I don't think this issue is fixed, I think the
> effect got broken somehow!

i didn't even pay attention to that... i'll go look again... i'm using "detailed 
weather" and selecting "stormy monday" at KMIA in parking space "Gate_D17"... 
this to get the rain real quick...

with those weather settings, there're some hugely strong winds... with the craft 
secure, the front gear breaks and sometimes it breaks a wing off... unsecure the 
craft and it blows across the tarmac like a paper plate :lol:

[time passes]

i have to retract my earlier statement... evidently i didn't spend enough time 
looking...

from INSIDE the craft i see the drops on the windows and i see them falling 
outside... i see these drops flowing if there's enough of them... i do NOT see 
the splashes on the ground or on the underside of the wings...

from OUTSIDE the craft, i see the drops on the windows and i see them falling 
from the sky... i see them splashing on the ground and top surfaces of the 
craft... if i move my (helicopter) view so that i'm under the wing looking up, i 
do also see the splashes on the underside of the wings...


it is funny this testing... this time i wasn't being blown all over the field 
and breaking gear and wings... the sim's HUD is indicating 30 to 45 knot winds 
but apparently i'm facing away from the winds because the airspeed indicator is 
just barely registering at the lower end of the scale with the pitot tube cover 
off... this is with the craft fully secure when before it was breaking stuff...

**Comment by gilbertohasnofb** [comment]
> i see them splashing on the ground and top surfaces of the craft... 

Really? I can't see any effect on the model except for the windows.

**Comment by wkitty42** [comment]
On 08/07/2016 11:19 AM, Gilberto Agostinho wrote:
>     i see them splashing on the ground and top surfaces of the craft...
>
> Really? I can't see any effect on the model except for the windows.


yes but it takes a while... i waited 10 minutes this time and changed the 
weather from "thunderstorms" to "stormy monday" a few times and then tried a 
couple of the CAT settings before i was able to see them... they show up as 
slightly lighter blotches... i tried to get a screenshot but the gears broke 
again and the rain stopped before i could get to F3 and take the shot...

[more time passes]

got'em! finally... can be hard to see, though... here's two images of the same 
screen shot... the first image is original and unmarked... the second has some 
splashes identified by circles around them... if you look closely, you can see 
others on the wing surface... the vertical stuff is the falling rain, of course :)


https://www.dropbox.com/s/z5o8hbah4zyf9cw/fgfs-screen-001.png?dl=1


https://www.dropbox.com/s/h7tyzvm4k5tjric/fgfs-screen-001-1.png?dl=1

**Comment by wlbragg** [comment]
>yes but it takes a while...

That is normal.

 I don't think there is anything we can do about this short of separating any object we don't want the effect on to not be included in the effect (ie: separating the top half and the bottom half of the wing and only including the top half of the wing in the effect.

Let me ask Thorsten and make sure this is a shader limitation.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
Doesn't the shader take into account the normals of the faces/vertices of the objects?

**Comment by wlbragg** [comment]
I just asked Thorsten that question.

**Comment by wlbragg** [comment]
Thorsten said he will see if he can check for surface being up, but it will probably be limit it to regular flight (not inverted), that might prove to be too expensive for the amount of gain.

**Comment by gilbertohasnofb** [comment]
Great!

> but it will probably be limit it to regular flight (not inverted)

Sounds reasonable.

**Comment by wlbragg** [comment]
Thorsten pushed the fix for this so it should be good to go.

**Comment by onox** [comment]
@wlbragg Can you confirm that Thorsten's fix fixes this issue?

**Comment by wkitty42** [comment]
On 08/08/2016 04:30 PM, onox wrote:
> @wlbragg Can you confirm that Thorsten's fix fixes this issue?

i think i can... i just went and tested it with a CATII at St. Bart's at 
noonish... i was able to see the splashes on the top of the wing (finally) and 
none on the bottom like it was when i first reported it... we'll let someone 
else confirm it as well, if you like...

i do like the water cloud that moves back behind the craft when the engine 
speeds up and slows down... i could see a bit of it around the craft with the 
engine running at idle... very nice! :)

**Comment by wlbragg** [comment]
>@wlbragg Can you confirm that Thorsten's fix fixes this issue

I guess we'll have to take @wkitty42 word for it. :smile:,  am not ready to pull a new fgdata.
