### ISSUE TITLE
Loading the aircraft with the engine running

### ISSUE THREAD

**Issue by Juanvvc** [Juanvvc/c172p-detailed#739]
Maybe related to #363 

Some users prefer loading the aircraft with the engine already running. This could also an interesting feature for the tutorials.

Please, check my post in http://forum.flightgear.org/viewtopic.php?f=25&t=29206&p=280838#p280838

Do you think the listener for "/sim/signals/fdm-initialized" in c172p.nas could check if "/controls/engines/engine/current-engine/running=true" is set and if it is, call autostart() and set throttle=1?

**Comment by onox** [comment]
It would be nicer if this is generalized so that FG's launcher gives the user the option to choose from a selected "state" (cold-and-dark, running, in-air, etc.)

**Comment by gilbertohasnofb** [comment]
> Some users prefer loading the aircraft with the engine already running.

Is there a problem with the option "start with engine running" which is currently available in the aircraft menu? It seems to work for me.

**Comment by Juanvvc** [comment]
> "start with engine running" which is currently available in the aircraft menu? It seems to work for me.

I was not even aware of that option! This option (linked to "fdm/jsbsim/running") is defined to be saved in the aircraft-data section, and it can't be overwritten in the command line.

I can confirm that if you set this option in sim (but not in the launcher), the next time you run flightgear the engine starts automatically. I'm not sure if the c172p should overwrite "fdm/jsbsim/running" if passed in the command line but as onox says, it is something that should be generalized for all aircraft.

Ok, I'll explain this option in the forum. Thanks!

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by wlbragg** [comment]
I just posted that there is the "start with engine running option" before I read this issue.

**Comment by Juanvvc** [comment]
There is an ongoing discussion in the devel list about this topic. This is the first message:

https://sourceforge.net/p/flightgear/mailman/message/34974270/

The current agreement seems to be setting the "start with engine running option"  to ON **by default**. Another alternative is using the c172p variant file I posted in the forum (after checking for its correctness)

What you think about this discussions? I think they have some good points.

**Comment by gilbertohasnofb** [comment]
> The current agreement seems to be setting the "start with engine running option" to ON by default

I disagree with that. The option is given in the aircraft dialog and if an user can't even bother to check the aircraft options in its menu then maybe flight sim isn't really for him/her (flight sims are, by definition, complex things). As for the argument "we're right to be proud of the sort-of realistic-ish engine startup sequences for some of our planes, but let's not force them down the new users' throats", I believe the complex options of our plane are not forced on by defaut (like complex start up procedures, aircraft tiedowns and chokes, fuel contamination, etc.). I tested now and with the option "complex start up procedures" disabled, and by simply pressing `S` the engine turns on (no need even of using autostart). Also, I never seen a flight sim nor flight sim addon which starts with the engine on, and I think there is no reason to do that for our plane.

Finally, here is a thought: as much as a newbie might be frustrated that he doesn't know what to do when firing up the plane for the first time and might not be able to start and engine, so might happen to an experienced RL pilot which is not a computer savvy, and which might as well have a horrible impression of our aircraft and sim because the Cessna startup is utter unrealistic, and this person might be as likely as the newbie to ignore the menu options. So to whom do we want to cater for?

> Also, some developers report the autostart option is not working. This option always worked for me. Maybe their tanks are drained?

It has absolutely always worked for me, and I used it a thousand times. If their fuel level is too low, they should see a warning message `Warning: fuel level of the left tank lower than 25%!` in the screen

> Finally, David suggests not to be too picky with the position of the throttle (0.2<throttle<0.5)

I would change that only if those values are not reasonable with RL. Do you think a RL throttle is more forgiving while starting the engine? If so by how much? Some people wrote that you open the throttle "just a crack" when starting the engine, so maybe the lower bound could be even lower?

**Comment by wlbragg** [comment]
>We're giving a poor first-time user experience by starting the 172P
with the engine off (I just experienced this again trying to help a
first-time user via chat, and watching his enthusiasm drain as he couldn't
get the engine running, even with autostart)

I don't buy it, the autostart always works. You do have to press the "s" after clicking on autostart, it tell you to do this.
The c172p has three startup states, more than any other aircraft. Of which each one will persist upon save. It doesn't get much easier than that.

> - If we're aiming for realism, it's a failure -- you would *never* be at
   the runway threshold of a major airport with your engine off (unless it
   were on fire).

That is a good point.

>Could we reconsider launching by
default with the C172P engine running, with a menu option to start at the
tiedown spot with the engine off, for people who want it?

Another good point and a nice feature.

>More seriously, we're right to be proud of the sort-of realistic-ish engine
startup sequences for some of our planes, but let's not force them down the
new users' throats; it's better to let them discover them as they become
more advanced.

I think we left it very easy to figure out how to get along with this aircraft. But he does make good points. There is nothing wrong with or keeping us from making the default the easiest of all options with the other harder options available in the menu.

>- By default have the engines running/brakes on and be ready to go after fg
startup (at least first-time startup)
- Alternatively and _actively_ select some kind of advanced/realistic mode
and start with a cold aircraft.

Because this is the default aircraft (the only aircraft) I have to agree. This makes the most sense for a default startup for the first time user/install.

**Comment by Juanvvc** [comment]
> It would be nicer if this is generalized so that FG's launcher gives the user the option to choose from a selected "state" (cold-and-dark, running, in-air, etc.)

James Turner has just proposed a system very similar to the one described by onox: https://sourceforge.net/p/flightgear/mailman/message/34975108/

After that, Torsten proposed a more general approach, letting the aircraft define its own states (I guess that in the sim section of the -set file): https://sourceforge.net/p/flightgear/mailman/message/34975174/

I guess that, being the default aircraft, the c172p project is not completely free to decide how the aircraft must be started. Please, take an eye on the discussion in the devel list! There are some interesting ideas over there regarding this topic.

**Comment by onox** [comment]
> Because this is the default aircraft (the only aircraft) I have to agree. This makes the most sense for a default startup for the first time user/install.

If FG was a game I would agree with you, but FG is not a game, it's a simulator. If someone downloads FG and then does not do any effort to find out that you have to press `s` and immediately gives up, they I would rather see that person stops using FG, because I prefer people who don't give up so easily.

> I guess that, being the default aircraft, the c172p project is not completely free to decide how the aircraft must be started

Sure we are. We just say no and dig our heels in. Thorsten often does the same thing and it works for him.

We could define a list of states (subset of a formalized set of states) that is valid for our aircraft and then the Qt launcher shows a combobox with those states that the user can select. The launcher then sets the chosen state in `/sim/initial-config`.

**Comment by wkitty42** [comment]
On 03/29/2016 11:57 AM, Gilberto Agostinho wrote:
[trim]
> contamination, etc.). I tested now and with the option "complex start up
> procedures" disabled, and by simply pressing |S| the engine turns on (no need
>  even of using autostart). Also, I never seen a flight sim nor flight sim
> addon which starts with the engine on, and I think there is no reason to do
> that for our plane.

there is a great desire for this capability if one is starting with the "on 10 
mile final" option from the launchers... or, for that matter, any other "already 
in the air" positioning...

when i finally get around to wanting to practice my landings, i expect that i 
will be using the "on 10 mile final" option from the launchers... getting the 
craft started for that scenario without falling out of the sky or having to 
circle back around and climb back to altitude is not something that one should 
have to do...


NOTE: i don't remember the exact wording of this location option in the 
launchers but it is definitely starting at "10 miles" out aligned for landing...

**Comment by wlbragg** [comment]
>If someone downloads FG and then does not do any effort to find out that you have to press s and immediately gives up,

While that is a true and I don't disagree, any user beyond a complete novice knows how to use the menus and options and can one time, (heck they already have), put the sim into the state they want. It's the first time user and really the very first time you install and load the sim that were talking about here. We can make it idiot proof or not. I think it should be idiot proof. It just make the most sense to me.

**Comment by onox** [comment]
But if we assume that the user is too stupid to know or be able to press the `s` key, we should also assume the user doesn't know that 3/9 or pagedown/pageup keys are used to control the throttle.

I think it's better that first time users are asked a question whether they would want to follow some tutorials to learn how the sim works.

**Comment by onox** [comment]
A bit off-topic, but FG should get a configurable keyboard mapping. Having to specify key codes or keys is bad. Instead aircraft should be able to specify and use "actions" like "increase_throttle", "increase_flaps", etc. These actions then have certain default key codes or keys. In a non-aircraft specific GUI window the user can then optionally map an action to a new key.

**Comment by gilbertohasnofb** [comment]
Given the work we did on the autostart function in the PR https://github.com/Juanvvc/c172p-detailed/pull/758 (now not even requiring that the user press "s" in the keyboard, as well as taking care of oil, fuel, flaps) and given that we do have an option to start the sim with engine running, should we keep this issue opened?

**Comment by wlbragg** [comment]
I don't know about this issue, but I really want to look into starting the aircraft at hanger or start up position (gate) if not using the "Start With Aircraft Running" option. It just makes sense that if you choose the "Start With Engine Running" option you should be at the runway and ready to go. On the other hand if you start with what used to be the "Complex Startup" now the default, you should start up at a hanger or gate. I thought I tried to start at a location other than the runway recently and it didn't work. Is that option broken in FG?

**Comment by wkitty42** [comment]
yes, parking has been broken for several months... i'm not sure if it is totally 
repaired at this time... some airports seem to have working parking choices 
again but for some reason not all of them are working... in some cases, i have 
to use the location menu in the sim's F10 menu bar to select the (same) airport 
and then the parking position i want to start with... all of this is with the 
internal Qt --launcher...

**Comment by gilbertohasnofb** [comment]
@wlbragg that would be great, but there are two problems that comes to mind: 1) as pointed out by @wkitty42 the parking is currently broken, but maybe even more fundamentally 2) how can we recognize if the aircraft is starting at a runway or not? Do you think in terms of having an option in the launchers? If so, then comes the problems that FG has tons of launchers, and though the official launcher right now is the Qt5 a lot of folks (myself included) use FGRun or something else. This just looks like having the potential of breaking the fun for a lot of people... But if it's doable somehow, then hey, that would be excellent! :smile:

**Comment by wlbragg** [comment]
I never really stopped to think about the logistics of it.

>how can we recognize if the aircraft is starting at a runway or not?

When do we not start at an airport?

I envisioned an aircraft specific choice not really considering the GUI.

If persistent data is left on complex startup "the default now" then if user selected a parking spot in launcher, use that else choose random parking spot at the startup airport.
or
If persistent data is left on start with engine running, then start on runway of GUI choice.

I don't know if we even have access to the users GUI choice of parking or runway or best runway?

Also when the GUI parking is working, then I guess we already have that option and it may make more sense to leave it there VS aircraft specific.

Some of the previous GUI capabilities are not well thought out in my opinion. This is one of them. I think after some though on the subject. If your giving the choice in the GUI it should have been
Start "Running", on runway in takeoff condition, brakes on.
Start "Realistic", cold, everything done at a parking spot.
And of course any specialized choices such as "In Flight" or possibly "Taxiing" or "In Tow". Just my opinion.

If the parking is working in the "defacto" launcher, then maybe this is not the place to discuss this?

**Comment by gilbertohasnofb** [comment]
> When do we not start at an airport? Unless you mean "on the runway or not"?

I mean, as far as I understand what you want to implement is the following: starting on runway == engine on, else starting at a parking positions == engine off. The problem is that there is no way of recognizing if you are on a runway or not in the sim, just in the launcher, right?

> If persistent data is left on complex startup "the default now" then if user selected a parking spot in launcher, use that else choose random parking spot at the startup airport.
or
> If persistent data is left on start with engine running, then start on runway of GUI choice.

That's clever but personally I think it will be quite confusing to users. Imagine someone doesn't have the "start with engines on" option ticked, and so the person starts on a parking spot regardless of his/her choice. Now this may look very confusing, and I can already imagine tons of people writing "why I can't start on the runway?!". This kind of forcing of parking spots seems to me to be a bit problematic.

I also wrote before that almost every flight simulator I know handles this by leaving it up to the user to start wherever they want (runway or parking) and allowing the user to start with engine on or off. Then it's up to the user to make things realistic or not.

But yeah, that's just my 2 cents.

**Comment by wlbragg** [comment]
Good enough, let's hope that this is fixed in the sim and remains that way. As long as there is a choice to start at a parking spot, cold, I don't really care which method is used (sim or aircraft).
