### ISSUE TITLE
oil dialog doesnt work when on floats (drifting with wind)

### ISSUE THREAD

**Issue by tigert** [Juanvvc/c172p-detailed#743]
Looks like the oil check dialog is too strict about aircraft movement, as when you are on floats, it says the dialog is disabled when the wind blows you around?

**Comment by gilbertohasnofb** [comment]
Oh, when I implemented the dialog it didn't cross my mind that the aircraft on water could have some reasonable speed. I will take a look at the conditions used for this dialog.

And what about the pitot tube cover, does it suffer from the same problem? If I remember correctly, it uses a similar if not identical condition as the dialog you mentioned.

**Comment by gilbertohasnofb** [comment]
@tigert Indeed the only condition used for the oil dialog is groundspeed < 1.0 knots:

```
<enable>
    <less-than>
        <property>velocities/groundspeed-kt</property>
        <value>1.0</value>
    </less-than>
</enable>
```

I suspect the pitot tube will have the same problem as it uses a near identical conditional:

@onox @wlbragg would you have a suggestion on how to handle this better? We could use AGL altitude, but then the dialog is active during the take off roll. Some proposals:

1) enabled if engine is off AND altitude AGL < 2.0 ft. This has the downside that some people will be mystified of why the pitot tube cover won't be removed while on the ground without realising it's because their engine is on. Also, the 2.0 ft in the proposal above is just an arbitrary value, as I don't know how reliable it would be to set it to == 0.0

2) enabled if EITHER groundspeed < 1.0 OR floats touching water. Is there some property for the latter, which recognizes if the hydrodynamic model is activated?

3) enabled if groundspeed < 20.0. Simply raise the value of the conditionals.

What do you all think?

**Comment by dany93** [comment]
Proper conditions are not easy to set because there are many possible situations.

I don't know this well, but here what I have seen by observing the properties:

To test the contact of wheels on ground
`/fdm/jsbsim/gear/unit[N]/WOW = true or false` if they are touching the ground or not
(from c172p.xml for the numbers)
N=1, 2, 3:  ground landing gears,
N=19 - 22:  amphibious float landing gears,
N=23 - 25: wheels and skis
No need to test everyone, but at least one of each set.

To test which kind of material is below:
`/fdm/jsbsim/ground/solid`
=true if the aircraft is above or on a solid ground (even if it is _flying_ above)
=false if the aircraft is above or on a water surface (even if it is _flying_ above)

To measure the hydro forces:
```
/fdm/jsbsim/external_reactions/hydro-X =
/fdm/jsbsim/external_reactions/hydro-Y =
/fdm/jsbsim/external_reactions/hydro-Z =
```
I think that X and Y can be used to test the displacement (gliding) on water (airspeed can be a bad criteria because there can be wind)
Z to test steady touching on the water

Not sure about all of this, but I hope it can start helping.

**Comment by gilbertohasnofb** [comment]
@dany93 thanks for the explanation, Dany! This looks promising, I will experiment with it. I didn't know that the WOW property also detect floats and skis, I thought it was only for the regular landing gear on solid ground!

That will probably do the trick, but the question concerning the engine status is still valid: do we with to limit the oil change dialog, as well as the tie-downs, pitot tube cover, chocks, etc., to be clickable only if the engine is off? In RL, nobody would do any of this with an engine on, so that's why I propose, but as I wrote before it can be mystifying to see that something is sometimes clickable and sometimes not when you don't know how it works in the sim, and from this point of view it's harmless to leave them active even if the engine is on.

**Comment by dany93** [comment]
Or maybe you can send a message like "NOT WITH THE ENGINE RUNNING"

**Comment by gilbertohasnofb** [comment]
Yep, that would solve everything. Sometimes I miss the obvious solutions :smile:

Ok, so I will try to take care of this soon.

**Comment by onox** [comment]
Try `/fdm/jsbsim/hydro/active-norm`

**Comment by tigert** [comment]
It could pop the dialog with just the warning that checking oil in a running engine is both dangerous and does not give any meaningful measurements in the dipstick either.

**Comment by gilbertohasnofb** [comment]
Would anyone come that close to a spinning propeller in RL?!

I like your idea. As for implementing it, let's think: currently the oil dialog opens regardless of the situation (mid air, on ground, engine on or off, etc.) but the slider can be dragged only if the plane is on the ground and with the engine off. So to have a pop up, I guess we would have to force close the oil dialogue as soon as the aircraft engine is on, and then the warning message would be displayed when trying to click on the oil cap hotspot while the engine is on.

In which case, can anyone please point out to me what would be the best approach to force close a dialog when the condition `engines/active-engine/running` changes to `true`, please?

**Comment by wkitty42** [comment]
On 04/16/2016 07:05 PM, Gilberto Agostinho wrote:
> Would anyone come that close to a spinning propeller in RL?!
>
> I like your idea. As for implementing it, let's think: currently the oil dialog
> opens regardless of the situation (mid air, on ground, engine on or off, etc.)
> but the slider can be dragged only if the plane is on the ground and with the
> engine off. So to have a pop up, I guess we would have to force close the oil
> dialogue as soon as the aircraft engine is on, and then the warning message
> would be displayed when trying to click on the oil cap hotspot while the engine
> is on.

why force it closed? surely we can have a dialogue open as well as a popup 
warning... if they open the dialogue when the engine is running then popup the 
warning "hey fool! the engine is running and you're too close to the prop!!" or 
whatever is wanted :)

**Comment by dany93** [comment]
> Would anyone come that close to a spinning propeller in RL?!

Sometimes, being close to the propeller with the engine running cannot be avoided. For tuning the carburettor or the idle RPM for example. Not for checking the oil...

**Comment by gilbertohasnofb** [comment]
Thanks for the feedback, everyone. You can test the results in the PR.
