### ISSUE TITLE
Return to a visible heading bug

### ISSUE THREAD

**Issue by geoffmcl** [Juanvvc/c172p-detailed#746]
Hi all,

At present only using the 'next' default c172p, version 2016.2.0.

Perhaps someone could remind me how to set up to use the latest from here. I keep the repo updated. Maybe this **Feature Request** has already been addressed, but could not find any references.

Originally the heading bug was like 2 large **orange teeth**. Very visible. As it should be.

Now it seems to be two very **faint** red lines, maybe just 1 pixel wide. Even with the illumination turned up to 100% they are still barely visible. you have to zoom in all the time.

Could we go back to the large orange markers please, if not already done.

**Comment by gilbertohasnofb** [comment]
That was actually my work, it was done when I redid all textures of the instruments. This is basically the current status:

![](http://s11.postimg.org/p50jvl66r/FG_0.jpg)

![](http://s11.postimg.org/bgkjtyaab/FG_1.jpg)

Personally, I don't see a reason to go back to the older model because the new model is based on a real instrument, see:

![](http://cdn-www.airliners.net/aviation-photos/photos/3/3/0/2558033.jpg)

**Comment by geoffmcl** [comment]
@gilbertohasnofb I **can** see it better in the RL image... thanks for the images and explanation...

First it seems a little **fatter** in RL than in the sim, and perhaps more importantly is **closer in**, on a smaller circle, hardly outside the tops of the letters,  while in the sim it is out mostly **beyond** the circle around to tops of the letters...

And the color seems more towards orange, not a dull red...

So the **Feature Request** is mainly to make it `more` visible...

And that is besides the idea that to make it visible on a screen, perhaps we do have to exaggerate RL a little...

Or add an accessibility factor as an aid to those of us with failing sight, but still want to enjoy flying...
When I turn this up the bug is enlarged, as could other instrument markers... just saying...

**Comment by geoffmcl** [comment]
More over, can you find it in the screen shot?

![fgfs-screen-007](https://cloud.githubusercontent.com/assets/1333435/15053236/e9492b96-1301-11e6-90db-c279e259ff49.png)

It is near the `W`... as I say if it was brought into the center more, it would occlude some of the white marks, was slightly thicker, and lighter in color...

**Comment by jarlarntzen** [comment]
+1 I agree.Need brighter color on the heading bug.  :-)

**Comment by onox** [comment]
@gilbertohasnofb This issue is about the brightness of the heading bug. It just needs to be brighter. I thought this was caused by the irradiance feature by @wlbragg, but excluding the object from the effect did not seem to solve it.

**Comment by gilbertohasnofb** [comment]
The colour of the bug has never changed in the png files, it's the same as before. And to be frank, I still don't see the problem: the thickness of the bug is pretty much the same as the RL and I don't think we should take "poetic licenses" and change things to make the sim easier; also, I find the irradiance effect quite realistic, looking at the instruments against the light or in the shadow is tricky, particularly if you are looking at them from such wide angles. See for instance:

![](https://i.ytimg.com/vi/y0A8849h1Uo/maxresdefault.jpg)

**Comment by Juanvvc** [comment]
This is a quite interesting discussion about the needs of a computer sim or using realistic models. I support Gilberto's highly detailed and realistic models, but  geoffmcl  has a good point. Gilberto, your models look gorgeous in high resolution, but geoffmcl seems to be using a monitor with a much lower resolution. Can you check the cockpit in a lower resolution monitor?

In any case, the discussion about the colour of the bug, which seems to be different for some of you, may show that something funny is happening with the shaders.  geoffmcl, could you please set the shader specs to the max (Menu View->Render settings->Maximize shader quality), and check if there is any difference?

Thanks!

**Comment by onox** [comment]
In RL you can easily and quickly bend forward to see the heading bug if you cannot see it normally. You can also squeeze your eyes if you have to, but doing these things in FG is difficult; you have to press and hold x and wait several seconds for it too zoom in.

And in the past (even after changing the looks of the instruments) the bug was clearly visible. Compare first picture in https://github.com/Juanvvc/c172p-detailed/issues/746#issuecomment-217225748 with https://github.com/Juanvvc/c172p-detailed/issues/746#issuecomment-217240153

**Comment by geoffmcl** [comment]
The discussion seems to focus on the color... well that may to be important, but @gilbertohasnofb says the color has not changed in the png...

But this misses the other point that it is now well outside the circle of letters -

![fgfs-screen-011](https://cloud.githubusercontent.com/assets/1333435/15073874/2dc98334-139c-11e6-9988-871fc43c90b5.png)

Whereas in the RL image it is different... and maybe that difference would help with visibility... if the fatter part was in next to the letter, and not almost out of the instrument... the above image is with 100% illumination, which is what I now use all the time...

And as @onox points out, in RL you can lean forward, squint... but using the x key takes time, and is distracting to flying...

And @Juanvvc, I tried changing the Shader 'performance' if that is what you mean... putting that slider up to max and fgfs.exe crashed... I can move it up from 1 to 3, but the bug is not more visible... or are you talking about something else... please explain...

And anyway, I would prefer it be clearly visible in the default... what a new user first sees, without getting into 'settings'... but will try other ideas...

PS: I run the monitor at 1920 x 1080 @ 60 Hz, on I think a big 23" monitor... I have not tried recently in an older machine with just 1024 x 768 on a 19" monitor, but expect the problem to be worse... where as I flew the sim for hundreds of hours in that old machine, and had no problem with the nice orange gopher teeth...

**Comment by wkitty42** [comment]
On 05/06/2016 09:39 AM, Geoff McLane wrote:
> PS: I run the monitor at 1920 x 1080 @ 60 Hz, on I think a big 23" monitor...
> I have not tried recently in an older machine with just 1024 x 768 on a 19"
> monitor, but expect the problem to be worse...

my old CRT monitor is 1600x1200 but i run fgfs with --geometry=1024x768... you 
could try testing different resolutions resolutions like that... oh, i also run 
it full screen, too...

> where as I flew the sim for hundreds of hours in that old machine, and had no
> problem with the nice orange gopher teeth...

personally speaking, it doesn't matter to me but if the current pointer is to 
remain, yes, i agree that it needs to be deeper into the circle of markings...

**Comment by geoffmcl** [comment]
Just to remind some of how **clear** it used to be, and how it was part of the circle of marking, this is from my old XP machine mentioned above...

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/1333435/15082303/59dc78ca-13c7-11e6-8c51-5f20f37a09ba.png)

And close up -

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/1333435/15082337/82a56ffa-13c7-11e6-961c-52a603bb1be0.png)

I think it is FG 3.5 IIRC...

**Comment by geoffmcl** [comment]
Oops, maybe 3.4, or 3.2...

**Comment by wlbragg** [comment]
I think maybe we should mover it ever so slightly closer to the white lines and make it a little thicker (just a small bit) and maybe change the color to be a little more red and not so dark. Then see if that is enough to make it visible on lower res systems.

**Comment by gilbertohasnofb** [comment]
Hi all, first of all sorry for my late reply, I have been quite sick these last days and I haven't had the chance to deal with these issues. Here are a couple of thoughts:

- @geoffmcl which screen resolution are you using? I will test how the cockpit looks in lower resolution, but we all must keep in mind that the idea of a good looking cockpit is to look as realistic as possible and NOT to optimize it for very low resolution screens
- as @onox has pointed out, the heading bug has been quite visible even after the modifications I made to this instrument, but it seems the irradiance effect is affecting it maybe too much. @wlbragg would it be possible to tone the effect down for this particular object or that is not possible?
- the bug indeed has to be extended a little bit as to look like the image below, and I will work on it straight away:

![](http://thumbs2.picclick.com/d/l400/pict/261798580737_/Directional-Gyro.jpg)

- I will also make it a little bit thicker, but not much else we are simply making up a non-existent instrument
- which brings to the point: reverting to the old bug while keeping the much prettier heading indicator is not possible, as that type of bug does not match this model
- about the colour: I am a bit afraid of changing the colour of the bug because of how the irradiance effect works. @wlbragg and I tried doing that with the artificial horizon and we simply didn't manage to get something decent... that is, the effect changes the colour a lot when the cockpit is dark, but then when the cockpit is illuminated properly the objects will also have the "compensated" colour. It's basically a choice of which situation do we want it to look good... anyway, I will take a look at this but I don't think this is solvable only by changing the texture colour

So I propose the following:

- I will extend and thicken a bit the bug
- I will also enlarge the whole HI a bit, since there is quite a lot of space between the letters and the borders of the instrument
- @wlbragg could take a look on the irradiance effect

As soon as I have the new textures (at most by tonight) I will create a PR

**Comment by gilbertohasnofb** [comment]
Okay, so I did tweak a bit the HI:

- the bug is now substantially thicker
- it also has a wider "base", so it should be much easier to spot

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/15118221/8db3597a-160b-11e6-8f6a-08ad6caaf3d1.png)

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/15118206/7b97a2aa-160b-11e6-95f3-aef78cc14a61.png)

Now... the problem of the bug disappearing due to the irradiance effect still persists. To make it clear, reverting to the old one would do _nothing_ to help this issue. Also, changing the colour of the bug wouldn't help either, as the saturation of the current texture is quite high and the saturation in the shadows in sim is extremely low. Compare these two shots from the same flight:

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/15118252/adb3c80e-160b-11e6-89a5-ab4d87e4fc99.png)

![fgfs-screen-004](https://cloud.githubusercontent.com/assets/5700795/15118253/adca77d4-160b-11e6-9a4e-b4684ad443c9.png)

@wlbragg I think we need to tweak the effect for this specific object if possible

**Comment by gilbertohasnofb** [comment]
By the way, I created and pushed a new branch called `bug-746` for those wanting to try it out. Once the issue of the shadows is tackled we can then open a PR.

**Comment by geoffmcl** [comment]
@gilbertohasnofb, thank you for the update... images look good...

Could someone point me to a Wiki about how I can pull and test this... 

I have pulled my `F:\Projects\c172p-detailed`, and checked out `bug-746`... 

Do I just add `--fg-aircraft=F:\Projects\c172p-detailed` to the fgfs command?

I mentioned earlier I use 1920 x 1080, and wonder what you 
specify as `very low resolution screens`... please explain...

Will try this... looks much better... at first glance... thanks...

**Comment by wlbragg** [comment]
>@wlbragg would it be possible to tone the effect down for this particular object or that is not possible?

Looking at it now, sorry for the delay.

**Comment by gilbertohasnofb** [comment]
@geoffmcl If you did a `git pull` on your master then checked out the branch `bug-746`, all you need to do is direct FG to load the aircraft from that folder. I don't know which command line option you have to use, but if you use FGRun you can simply add the folder of your local clone of the repo to load the plane. As for the resolution, my bad, there was a lot of text to read and I missed it... @Juanvvc had mentioned something about lower resolution and somehow I assumed it was your case, so please ignore that. If you are also running at 1920p, then the problem is really only due to the irradiance effect, as shown in the images above. So hopefully once this is tackled the new bug will be visible again at all conditions :smile: 

@wlbragg no problems, let me know if I can be of any help. While you are looking at this, I would suggest using the branch `bug-746` for that so you can tell how the effect is affecting the newest textures.

**Comment by wlbragg** [comment]
>I would suggest using the branch bug-746 for that

I am.
It's not the irradiance as far as I can tell. Shutting it off makes no difference.
I'm searching through the code to see if I can figure out what is causing this.

It used to work OK either with the old style or ever with the new one?

**Comment by wlbragg** [comment]
>It's not the irradiance as far as I can tell. Shutting it off makes no difference.

It would help if I looked at the right instrument, still checking this out. It could still be irradiance causing this.

**Comment by gilbertohasnofb** [comment]
> It would help if I looked at the right instrument, still checking this out. It could still be irradiance causing this.

Ha, that happens often to me during debugging as well. If it turns out the effect isn't causing it, then I can try to help to find out what else could be influencing it.

**Comment by wlbragg** [comment]
Giving its object a material definition (emission) seems to fix this. 
Add the HdgBug object to the material (emission) definition and test it.

~~~xml
 <animation>
  <type>material</type>
  <object-name>Face</object-name>
  <object-name>Front</object-name>
  <object-name>HdgBug</object-name>
  <emission>
   <red>1.0</red>
   <green>0.2</green>
   <blue>0.0</blue>
   <factor-prop>sim/model//material/instruments/factor</factor-prop>
  </emission>
 </animation>
~~~

**Comment by gilbertohasnofb** [comment]
I will test it right now

**Comment by onox** [comment]
You got `//` in there. Removing irraddiance effect indeed does not seem to make any difference.

**Comment by wlbragg** [comment]
I don't know if this causes other issues though because I have no clue really what this code is all about. Never learned about it in depth.

**Comment by onox** [comment]
It seems to work @wlbragg :+1:

**Comment by gilbertohasnofb** [comment]
Confirmed, that works! :+1: 

@wlbragg did you push this modifications or should I do it myself? Then I will create a PR and we can merge this straight away

**Comment by onox** [comment]
Hmm. It was already added to another material animation just below it?

**Comment by onox** [comment]
You should probably remove it from that animation.

**Comment by gilbertohasnofb** [comment]
That other animation also has a `//` on the property. Is that a typo?

**Comment by onox** [comment]
Think so yes.

**Comment by gilbertohasnofb** [comment]
Ok, I will test now with the `HdgBug` being only in the first animation but not in the second, and having both animation's `//` fixed to `/`

**Comment by wlbragg** [comment]
Yeah, those are typos. Looks good at night as well.
@gilbertohasnofb go ahead and make the changes yourself.

**Comment by wlbragg** [comment]
You need the second animation, that moves it?

**Comment by wlbragg** [comment]
Oh, right, the other materials, I didn't see it.

**Comment by onox** [comment]
I'm talking about the second "material" animation.

**Comment by onox** [comment]
There's one for Face and Front, and another for OBS-Knob, Hdg-Knob, and HdgBug.

**Comment by onox** [comment]
You could also leave HdgBug in that second animation. I don't know if these "material" animations are additive or whether they override the previous one.

**Comment by gilbertohasnofb** [comment]
I think they are additive since the first time we added HdgBug to the first, it fixed the problem even though it was present in the second

**Comment by wlbragg** [comment]
Yeah, remove it from the  OBS-Knob, Hdg-Knob, it probably got put there by mistake.
I just removed it and didn't notice any change.

**Comment by gilbertohasnofb** [comment]
though right now I tested it like this:

```
 <animation>
  <type>material</type>
  <object-name>Face</object-name>
  <object-name>Front</object-name>
  <object-name>HdgBug</object-name>
  <emission>
   <red>1.0</red>
   <green>0.2</green>
   <blue>0.0</blue>
   <factor-prop>sim/model/material/instruments/factor</factor-prop>
  </emission>
 </animation>

 <animation>
  <type>material</type>
  <object-name>OBS-Knob</object-name>
  <object-name>Hdg-Knob</object-name>
  <emission>
   <red>0.45</red>
   <green>0.09</green>
   <blue>0.00001</blue>
   <factor-prop>sim/model/material/instruments/factor</factor-prop>
  </emission>
 </animation>
```

with fixed `//` and HdgBug only in the first one, and it seems to work all well both during the day and at night

**Comment by wlbragg** [comment]
I think that is correct!

**Comment by gilbertohasnofb** [comment]
In that case, I will push the file and create the PR. You agree, @onox or is there still something potentially wrong with this xml file?

**Comment by onox** [comment]
Looks OK.

**Comment by gilbertohasnofb** [comment]
Ok, so I will create the PR now

**Comment by wlbragg** [comment]
I recall the first definition taking precedence, but I could be wrong. Not necessarily specific to "materials" but in general.

**Comment by gilbertohasnofb** [comment]
Really? When I was working with the regional textures, the last definition always overrode the previous ones

**Comment by wlbragg** [comment]
Then you may be right, I swapped the two definitions and it DIDN'T break it so you are probably correct.
