### ISSUE TITLE
save the state of the trim wheel

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#82]
Similarly to saving the switch and radio states, do the same for the trim wheel. Proposing behaviour:

- save the state of the trim wheel between sessions
- if autostarting (either via the menu or by unchecking the options "complex start up" and "start sim with engine running") then trim should be set to take off position, as to not complicate things for the beginners

**Comment by onox** [comment]
@gilbertohasnofb Do we really want this? The flight controls (surfaces) aren't saved either.

**Comment by gilbertohasnofb** [comment]
@onox Yes, I think it would be great. Flight controls are not relevant to be saved, but the trim is for the reason that the trim setting for landing is quite different than the trim setting for take off, and a pilot should always check this (it's part of the checklist). If we save the settings, we get a much more realistic procedure: just like in RL, we can't overlook where we last left the trim else the plane won't really lift.

**Comment by dany93** [comment]
True. But can you let things easy for beginners? Those who press "S" and that's all...
e.g. have the autostart take a preset or the -set value.

**Comment by gilbertohasnofb** [comment]
Well, I think we can have the autostart set the trim to the neuter position. As well, I already proposed to have an option in the menu which toggles saving the state between sessions or not (radios, knobs, toggles, trim wheel, etc.). To be honest, I think realism must be our main concern and if we are giving the beginners a chance to overcome the situation (e.g. auto start sets trim as well) then I am not really concerned if a beginner will screw something up.

**Comment by gilbertohasnofb** [comment]
And the benefit for people looking for realism outweighs the necessity of the noobs, IMO.

**Comment by dany93** [comment]
Do not forget that this aircraft is the first contact for FG beginners.
People looking for realism can find it, but you have already made very good efforts with the options to allow beginners use it quickly. I think it is important to keep this.

**Comment by gilbertohasnofb** [comment]
I understand, Dany, but do you think that making the autostart automatically set the trim wheel isn't enough? 

This is what I think: if a truly beginner doesn't know how to handle the start up procedure, the levers and switches, etc., then he can use autostart and problem solved, the plane is ready to fly. If someone else bothers to learn how to properly handle the plane, then he has a realistic atmosphere. Both are happy like this. I think that catering for beginners is fine, but there is a limit for that: I really dislike the idea of making the plane less realistic for someone who truly wants to experience realism just so that a beginner can fly it without autostart (even though he also doesn't know what a trim wheel is).

**Comment by dany93** [comment]
>...do you think that making the autostart automatically set the trim wheel isn't enough?

Yes, I think this is enough. What to ask for more?

Currently, I understand that there is, in Options, 2 possible checks for 3 sim start states :
1 - Start the sim with engine running (check / unchecked)
2 -  Complex start up procedure (check / unchecked)
3 - If 1 and 2 are unchecked, this is "autostart". Pressing "S" is enough. It works perfectly.
I presume they are saved for the next sim launch.
>if a truly beginner doesn't know how to handle the start up procedure, the levers and switches, etc., then he can use autostart and problem solved, the plane is ready to fly

Yes. If 3 is true. I guess this is the same with 1.
>If someone else bothers to learn how to properly handle the plane, then he has a realistic atmosphere

Yes.
>I really dislike the idea of making the plane less realistic for someone who truly wants to experience realism just so that a beginner can fly it without autostart

I completely agree but I don't understand why it is exclusive. Does the1 and 3 not respond for beginners? And 2 for experts?

**Comment by gilbertohasnofb** [comment]
@dany93 I think we are agreeing with each other in every thing here, so I will not try to reply point by point as to avoid any confusion (what you wrote above is exactly what I had in mind). So in that case, I guess we can decide on the following:

- let's save the state of the trim wheel between sessions
- if autostarting (either via the menu or by unchecking the options "complex start up" and "start sim with engine running") then trim should be set to take off position

**Comment by dany93** [comment]
@gilbertohasnofb  I agree.

**Comment by Juanvvc** [comment]
To me, saving the trim state makes much more sense than the position of the switches, for example :D Based on my experience when I get on an aircraft, I know the last pilot switched everything off for sure, but he DIDN'T reset the trim wheel. "Set the trim to neutral" is an item that appears several times int he checklists for a reason :)

**Comment by gilbertohasnofb** [comment]
Glad we all agree! So I updated the description.

**Comment by Juanvvc** [comment]
Also, I'm pretty sure a beginner is not going to use the trimmer during his/her first flights. The use of the trimmer and the necessity to set to neutral before taking off it is going to come naturally after a few flights. I don't think we should overprotect the beginner here.

**Comment by dany93** [comment]
Yes and no. Beginners often like to overpass the steps or explore, I see them well *trying to* use the autopilot.

**Comment by wkitty42** [comment]
i remember the first time i went hunting for a trim wheel... i never thought to look down at the floor between the seats or even to the lowest part of the panel... why? it wasn't right there in front of me and i simply didn't know that i could look around the craft like that :wink:

**Comment by onox** [comment]
I want to save the following additional properties:

`/controls/switches/magnetos`
`/controls/switches/master-bat`
`/controls/switches/master-alt`
`/controls/switches/master-avionics`

`/controls/gear/brake-parking`
`/controls/flight/flaps`
`/controls/flight/elevator-trim`
`/controls/engines/current-engine/throttle`
`/controls/engines/current-engine/mixture`
`/controls/engines/engine[0]/primer-lever`

**Comment by onox** [comment]
I'll save `/controls/flight/elevator-trim` in #285.

@gilbertohasnofb I think we shouldn't do "then trim should be set to take off position, as to not complicate things for the beginners" because beginners wouldn't know how to set the trim back to 0.0.

**Comment by gilbertohasnofb** [comment]
But I thought take off position == 0.0.

**Comment by gilbertohasnofb** [comment]
If it's not, then autostart could simple reset the trim to 0.0.

**Comment by onox** [comment]
> If it's not, then autostart could simple reset the trim to 0.0.

That's a good idea, `autostart()` doesn't do that currently.

**Comment by onox** [comment]
Takeoff trim is -0.1, btw.

**Comment by gilbertohasnofb** [comment]
Thanks!

**Comment by wkitty42** [comment]
On 07/08/2015 03:04 PM, onox wrote:
> I'll save |/controls/flight/elevator-trim| in #285
>
> @gilbertohasnofb I think we shouldn't do "then trim should be set to take off
> position, as to not complicate things for the beginners" because beginners
> wouldn't know how to set the trim back to 0.0.

i never set the trim back to 0 anyway because i turn the AP on as soon as 
possible to be able to have stable and easier flight with the KB... the AP 
adjusts the trim all the time when climbing or descending... if you turn off the 
AP, it is hard to see where the trim should be for zero unless you zoom way in 
and then you can't see out the windscreen or see any of your other 
instruments... while messing around down there, it is easy to knock some other 
setting by accidentally hitting the wrong key and you lose control of the craft...

yes, with the keyboard... this is the bottom of the stack and keyboard users 
should not be thrown out regardless of mouse or joystick... that's just not 
right... who are ""we"" to tell others that they have to use a mouse or joystick 
to be able to fly this basic and introductory craft??

**Comment by gilbertohasnofb** [comment]
> this basic and introductory craft??

I don't see this plane as a basic and introductory plane but rather as a complex simulation of a real life 172. And like in real life, the plane is not overly complicated but one needs to know a thing or two about how to handle it, how its system works, etc.

As for the trim, autostart setting it to 0.0 seems really reasonable, regardless of this mouse/joystick/keyboard issue.

**Comment by wkitty42** [comment]
On 07/08/2015 05:13 PM, Gilberto Agostinho wrote:
>     this basic and introductory craft??
>
> I don't see this plane as a basic and introductory plane but rather as a complex
> simulation of a real life 172. And like in real life, the plane is not overly
> complicated but one needs to know a thing or two about how to handle it, how its
> system works, etc.

i meant that it is the default craft which makes it "basic and introductory"... 
but whatever... i grow tired of trying to ensure that keyboard users are not 
left out in the cold...

> As for the trim, autostart setting it to 0.0 seems really reasonable, regardless
> of this mouse/joystick/keyboard issue.


ummm... really? the checklist calls for -0.1 or some such (one tick back) and i 
see the pointer move on the HUD when i click the autostart without complex 
turned on... i've never used complex because i didn't want to go that route 
thinking that it involved more work on my part...

my standard procedure every time i get in this craft:

1. SHIFT-X twice to see the top of the HUD without mucking view orientation
2. SHIFT-B to set the parking brake
3. click the yoke to get it out of the way
4. environment->weather->OK to turn on real weather engine
5. click autostart
6. hold 's' for the engine start
7. set heading bug to align with runway (F11)
8. adjust AP altitude to 2000+ to stop incessant beeping
9. max throttle
10. release brake
11. steer as best as possible down center of runway
12. down arrow one time at 55 kts
13. get ready to catch roll to left as we lift off
14. turn on the AP ASAP
15. adjust the AP for 0 ascent/descent and build speed
16. set AP for HDG ASAP
17. set AP to climb - max 700fpm
18. try to have fun

**Comment by gilbertohasnofb** [comment]
@wkitty42 I don't think we need to argue too long about this because regardless of how the user controls the plane (joystick, keyboard, mouse), the user can ALWAYS use the keyboard shortcuts for trim, or scroll over the trim with the mouse. This discussion is about what to do in case of users which are clueless about trimming: if we set the trim to -0.1, the aircraft will be trimmed slightly down during flight. If we set the trim to 0.0, then the aircraft will be slightly off trim for take off.

To be honest, the difference is so small that it barely worth the discussion. It's just a single tick difference! In RL, we don't have tooltips to set things that precise, and I am sure that trimming for take off means to get the trim needle as close as possible to the reference line.

**Comment by dany93** [comment]
This trim value is not a matter of chance. It is the result of the tuning of the horizontal stabilizer effect with elevator centered and trim = 0.

With default configuration, no flaps:
- elevator trim = 0 ==> climbing 80 - 90 KIAS (for 70 - 85 KIAS POH).
- elevator trim = -0.03 ==> climbing about 80 KIAS 
- elevator trim = +0.1 ==> cruise at 108 - 110 KIAS.
- elevator trim = -0.1 ==> climbing 69 - 72 KIAS: The pilot has to slightly push the yoke for climbing (70 - 85 KIAS), and push much for cruise (100 - 120 KIAS).

Elevator trim = 0 is a compromise for climbing and cruise.  The pilot has to slightly pull the yoke at climbing, slightly push at cruising velocity.

**Comment by wkitty42** [comment]
On 07/08/2015 05:47 PM, Gilberto Agostinho wrote:
> @wkitty42 I don't think we need to argue too long about this because
> regardless of how the user controls the plane (joystick, keyboard, mouse),
> the user can ALWAYS use the keyboard shortcuts for trim, or scroll over the
> trim with the mouse. This discussion is about what to do in case of users
> which are clueless about trimming:

agreed... plus i'm not arguing... i do not(!) and never have(!) argued... i 
don't even ""debate""... i state my side and then may try to clarify it in 
subsequent discussions...

> if we set the trim to -0.1, the aircraft will be trimmed slightly down during
> flight. If we set the trim to 0.0, then the aircraft will be slightly off
> trim for take off.

whatever the checklist calls for, i don't know... i just know that the couple of 
times that i've followed them, clicking on the ""do it"" button sets the trim to 
something... i only wrote -0.1 because i saw someone else write that earlier... 
frankly, i don't know what it is supposed to be set for and don't really care 
because we can still get off the ground without it being set... it just takes a 
little more runway room :shrug:

> To be honest, the difference is so small that it barely worth the discussion.
> It's just a single tick difference!

there is that, too... i was actually surprised that it took only one push of the 
button (i don't remember which one) to satisfy the checklist but there it is/was...

> In RL, we don't have tooltips to set things that precise,

that's true and kinda part of what i was pointing to... in a very round'about way...

> and I am sure that trimming for take off means to get the trim needle as
> close as possible to the reference line.

what reference line? ;) we're either set to 0.0 equal to a reference line or 
we're not... there's only one reference line TTBOMK... at least, there is only 
one in this craft and it can be hard to see as another member pointed out in an 
issue some couple of hundred numbers back ;)

**Comment by gilbertohasnofb** [comment]
@wkitty42 agree with basically everything you wrote. Just want to clarify something:

> what reference line?

I meant the arrow on the side of the trim written "take off". That's the reference for take off. For flight, we should trim for a certain speed and power combination, as Dany explained above.

**Comment by dany93** [comment]
@wkitty42 wrote
> sets the trim to something...i don't know what it is supposed to be set for and don't really care

By flying with the keyboard or even the mouse you cannot make the difference because you do not feel a centered position (a spring with a joystick, or the possibility of loosen the yoke in RL).
When the aircraft is well trimmed (for the velocity that you want) you can loosen the yoke and is goes on its trajectory. Yours controls are more accurate, just some pressure up and down, you can look at at map,...

**Comment by wkitty42** [comment]
@gilbertohasnofb 
> I meant the arrow on the side of the trim written "take off". That's the reference for take off.

oh! on some liveries, you cannot see the pointer... EI-MCF, N301DP, N6575E...

> For flight, we should trim for a certain speed and power combination, as Dany explained above.

agreed to a point... as i noted previously, if one uses the AP, the trim is controlled by the AP all the time... trim and yoke, both, as i recall but will have to go fly to be sure about that last statement...

**Comment by wkitty42** [comment]
@dany93 
> By flying with the keyboard or even the mouse you cannot make the difference because you do not feel a centered position (by the return spring of a joystick, or the possibility of letting the yoke go in RL).

true but you can see it move in the HUD much of the time... i generally also tell by the altitude in the HUD increasing or not in small increments depending on the severity of the trim setting when everything else is centered via '5'... this is more easily seen with the bluebird or the UFO, though, since they easily maintain a steady state and orientation...

aside from that, i agree with the rest of what you wrote... properly trimmed craft hold their level and velocity allowing for minute adjustments when needed... there's a lot of times that i see the AP has placed the craft into a 1 to 3 degree nose down attitude when flying at 100+ kts... the AP has done this via the trim as the indicator in the HUD is raised above the central neutral line...

**Comment by gilbertohasnofb** [comment]
@wkitty42 

> oh! on some liveries, you cannot see the pointer... EI-MCF, N301DP, N6575E...

Didn't realize that, I will fix that by tomorrow.

**Comment by gilbertohasnofb** [comment]
See #389
