### ISSUE TITLE
Oil consumption on aircraft weight and CG: subtract consumed oil weight

### ISSUE THREAD

**Issue by dany93** [Juanvvc/c172p-detailed#851]
Following https://github.com/Juanvvc/c172p-detailed/issues/847 and my remark https://github.com/Juanvvc/c172p-detailed/issues/847#issuecomment-256036968, I have changed the way oil weight management is done, to merely **subtract** the **consumed oil** from the "Basic Empty Weight" at the engine location.

dany93 Branch: [consumed-oil-weight](https://github.com/dany93/c172p-detailed/tree/consumed-oil-weight)

The current way, chosen by @gilbertohasnofb (subtracting the oil content for each engine from the basic empty weight, then adding it as an extra weight) is very confusing and uselessly complicated. Moreover, it needs recalculating the centre of gravity with no oil such that it will match the Basic Empty CG (with oil) from the POH. After that, JSBSim does the reverse calculation just to (hopefully) find again the POH CG. Also, one need to calculate the extra point mass location for the 180 hp with no oil (to match 180 hp POH-CG with oil). I've done all these calculations. They are not really complicated but very tiresome and prone to mistakes. JSBSim does all of this very well by itself. After that, many explanations are needed in the file comments to help those who will try to understand this. I pity the future maintainers for having to go through it ...
On top of that, all these calculations (weight, CG, extra weight location with no oil) are to be redone at each change which may happen in the future (I intend to to do such a change but prefer to wait and include it in a later PR commit for clarity).
Useless to say that starting from Basic Empty Weight and CG location taken from the POH is much more simple.

Concerning the weight and CG management, I think that my changes work (however not forgetting a configuration is hard). But I had to change (to correct?) a few points and I'm not sure that I've understood well what @gilbertohasnofb  wished. I would prefer to make that clear before doing a pull request.

1- In the FDM, I read:
```
        <!-- Extra weight due to oil quantity -->
        <pointmass name="extra weight oil">
            <weight unit="LBS"> 0 </weight>
            <location name="POINTMASS" unit="IN">
                <x> -0.886 </x>
                <y> 0.316 </y>
                <z> 0.082 </z>
            </location>
        </pointmass>
```

which sets this weight at coordinates which are different from the engine coordinates, which are:
```
                <x> -19.7 </x>
                <y> 0 </y>
                <z> 26.6 </z>
```
I've changed this. Am I correct?

2- In gui/dialogs/aircraft-dialog,
"Allow carburetor icing" (line 137 -151) sets the oil level at 7. Why ? I do not see the connection.
I've deleted this.

3- In gui/dialogs/aircraft-dialog,
"Allow oil management" ON or OFF did set the oil level to 7 (whatever the engine): I've set the oil at 7 or 8 depending on the engine. It works well except (maybe??) for one point: at the _simulator start_, I've seen the oil level set to 7 starting with the 180 hp engine (?? I cannot reproduce it...). That's not a matter of weight (the aircraft weight is managed by the initial basic empty weight and the consumed oil), only a matter of engine failure when the oil level becomes too low. I do not find how to implement this initializing change. I will let you to fix it, if necessary.

**Comment by gilbertohasnofb** [comment]
@dany93 I believe your approach sounds better, so I have no problems in it replacing the previous solution :smile: 

As for your comments/questions above:

1 - I don't understand what you mean, but I haven't changed any x/y/z parameters, only the total weight. See: https://github.com/Juanvvc/c172p-detailed/pull/848/files

2 - gosh, thanks for catching this! I must have introduced this without realizing while working on the carb icing, I will make a PR straight away! :blush: 

3 - I believe I did that so that if one would disable the oil management checkbox, then the oil would be reset back. It is a very clumsy way of doing it, and I think maybe we should remove that binding and simply improve the oil consumption function. That might solve the simulator start issue you are commenting. I am working on it on the same PR as for the issue above

**Comment by dany93** [comment]
Hi @gilbertohasnofb ,

1 - You did not _change parameters_, you [added these lines](https://github.com/Juanvvc/c172p-detailed/commit/6963a18981caf118d5cba525bb734b1fc14e0b6a) to take in to account the oil quantity.

3 -See [my comment in your merge request](https://github.com/Juanvvc/c172p-detailed/pull/852#issuecomment-258028083)

**Comment by wlbragg** [comment]
How much oil has to be consumed in pounds before the engine fails?
I know we manage fuel because it can fluctuate enough to effect the aircraft. But the oil? Your oil level typically will be stable within less than a pound or two. Why are we going through this much effort on the weight side of it?

**Comment by dany93** [comment]
@wlbragg 
+1
That was exactly my opinion in https://github.com/Juanvvc/c172p-detailed/issues/847#issue-185099773 and https://github.com/Juanvvc/c172p-detailed/issues/847#issuecomment-256036968

> But the difference is so weak that, in my opinion, the effect of oil consumption on the aircraft weight might be neglected. It would not be a noticeable fault and it would avoid adding useless complexity in the files.

> How much would the error be if the consumed oil was not taken into account?

**Comment by dany93** [comment]
@gilbertohasnofb 
You've gone too fast with [your PR](https://github.com/Juanvvc/c172p-detailed/pull/852#issue-186931418). You've changed the same files as I did.
My code, aside from the weight effect, fixes (almost?) all of the bugs on oil content vs the engine.
As you seem to agree with it, would you mind if we merged it first? Then, we will observe which bugs subsist  (if any) and possibly fix them.

**Comment by gilbertohasnofb** [comment]
> As you seem to agree with it, would you mind if we would merge it first? Then, we will observe which bugs subsist (if any) and possibly fix them.

No problems Dany, let's do it that way! Since your code solves the issues with the oil function, I think all that will be left for me to do is to remove those bindings from the gui dialog which are setting the oil level to 7 quarts whenever one enables/disables carb icing and oil management. So I will redo that later.

> I've made several tests, could not reproduce the bug oil level = 7 at start with 180hp, even with Allow oil management unchecked. It seems that everything works as expected (although why it does is not certain for me). Is the dialog box content read at each start? If yes, that would be the right way to get this.
> Did you check? Did you make tests?

I will take a look at this while testing your branch, but if your code is making it work as it should then no problems I suppose!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/Juanvvc/c172p-detailed/pull/853 and https://github.com/Juanvvc/c172p-detailed/pull/854

**Comment by wlbragg** [comment]
I have a question regarding the oil system and rather than add a new issue I figured I could just ask here.

I noticed a comment in the code
>just above oil minimal level makes engine cough

Does the c172p have a "low oil" kill switch? I'd be really surprised if that were true. If not, why would low oil cause the engine to cough? Typically an engine wouldn't do anything from low oil except over heat and then eventually seize up. This probably wouldn't happen until the oil was virtually gone, at least the seize up portion.
 How is the engine lubricated? Is it a gas oil mix or typical crankcase lubrication like a car?

**Comment by gilbertohasnofb** [comment]
> Does the c172p have a "low oil" kill switch?

Yes, see `/Systems/engine.xml`. The value is set to `4.92`. It also has a "cough switch" in the same file, for when the oil is just above `4.92` (or when the fuel is contaminated).

> This probably wouldn't happen until the oil was virtually gone, at least the seize up portion.

According to the POH. the critical oil level for both types of engine is 5 quarts, which is why I used the value I mentioned above.

> Typically an engine wouldn't do anything from low oil except over heat and then eventually seize up.

So you are saying an engine about to expire due to low oil would not cough? Should we remove the low oil condition from the coughing function?

> How is the engine lubricated? Is it a gas oil mix or typical crankcase lubrication like a car?

I don't know.

**Comment by wlbragg** [comment]
>Does the c172p have a "low oil" kill switch?

I have an electrical generator that has a built in low oil kill switch. When the oil gets below a certain level the engine ignition is actually shut off. There is a float in the crankcase that controls this action. That is what I meant by a "kill switch". It is a physical switch inside the crankcase. So if the c172p actually has this device then a sputtering could be a symptom of the oil dropping to the level where a bit of oil sloshing could cause it to try to kill the engine momentarily and then not.

**Comment by gilbertohasnofb** [comment]
@wlbragg from the other thread:

> I'm not sure what is meant here, What happens at the minimum?

I read it as "minimum oil quantity for safe operation of the engine", i.e. anything lower and you might need to buy a new engine for your aircraft. But as I said, the 172's POH state on page 4-6 "do not operate with less than five quarts. Fill to seven quarts for extended flight". 

> That is what I meant by a "kill switch"

I see now, we have been speaking about two different things. I meant that we have a function that kills the engine if the oil is too low, simulating an engine that has stopped to work. I am not sure if the O-320 has such device that you speak about, but I actually doubt it: it seems to me that is better to let an engine run for as long as possible instead of killing it _before_ it dies, since killing an engine in the air might as well lead to a crash.

So concerning the implementation here, I was suggesting that when the oil reaches a value of around 2 quarts then the engine would be killed.

**Comment by wlbragg** [comment]
>I am not sure if the O-320 has such device that you speak about, but I actually doubt it: it seems to me that is better to let an engine run for as long as possible instead of killing it before it dies, since killing an engine in the air might as well lead to a crash.

That is kind of what I figured.

OK, so if the engine oil drops to the level where the engine fails it is usually very abrupt. I actually had this happen on a small engine this past year. It leaked all it's oil out before I realized it and got so hot it virtually seized up, suddenly. I really can't say with any certainty if there was any noticeable change in rpm before that happened. But I can't imaging it doesn't slow down at least a bit. But there was no sputtering. Only a really nasty sound of metal to metal friction without lubrication, for a very short time.

>So concerning the implementation here, I was suggesting that when the oil reaches a value of around 2 quarts then the engine would be killed.

So yes, I think this is the right behavior. Maybe if not too much trouble, we could lower the rpm immediately prior to that. Not that you would have any time to do anything at that point. And even if you did shut the engine off at that first sign of trouble, it would lock up tight and not be able to be turned over after that due to the excessive heat.

**Comment by gilbertohasnofb** [comment]
> So yes, I think this is the right behavior. 

:+1: I will work on it

> Maybe if not too much trouble, we could lower the rpm immediately prior to that.

I think a filter could do the trick, I will see if I manage to code this. Or do you have some ideas on how to implement it?

**Comment by wlbragg** [comment]
>Or do you have some ideas on how to implement it?

Nope, go for it, I just want to steal it for the Cub when it's finished. :rofl:

**Comment by gilbertohasnofb** [comment]
> Nope, go for it, I just want to steal it for the Cub when it's finished. :rofl:

:laughing: :+1:

**Comment by gilbertohasnofb** [comment]
@wlbragg sorry for the mess but I worked on the oil in the same branch as the carb icing, this is because all these engine functions are related so it's way easier for me to keep track of what is going on
