### ISSUE TITLE
2016.4.1 is fast approaching

### ISSUE THREAD

**Issue by wkitty42** [Juanvvc/c172p-detailed#855]
in less than 10 days, 2016.4.1 should be released... is the craft is well enough shape to be branched for it? i thought i'd mention it so maybe we can get a leg up and not be rushed like we've seen in the past ;)

now that the oil thing is completed, if we could go ahead and branch ahead of the rush, i think that would be a GoodThing<tm>

**Comment by gilbertohasnofb** [comment]
@wkitty42 thanks for the heads up, I was not aware the next release will be so soon! But are you sure about it? Given that 2016.3 was released more than a month late, is 2016.4 still going to follow the original schedule?

@onox @wlbragg @dany93 @Juanvvc @dg-505 and all others, what do we still _really_ need to do before the release? For instance, I think we should really solve this one here https://github.com/Juanvvc/c172p-detailed/issues/849

Remember to also contribute to the list of features here: https://github.com/Juanvvc/c172p-detailed/issues/829

**Comment by wkitty42** [comment]
On 11/08/2016 05:05 AM, Gilberto Agostinho wrote:
> @wkitty42 <https://github.com/wkitty42> thanks for the heads up, I was not aware
> the next release will be so soon! But are you sure about it? Given that 2016.3
> was released more than a month late, is 2016.4 still going to follow the
> original schedule?

i think the schedule of every three months is still adhered to... at least, i/we 
can only look at the wiki to see...

   http://wiki.flightgear.org/Release_plan

i did also post something about being less than ten days away from release to 
the dev list where james said he was traveling for the next week or two... that 
mainly to point it out so that we don't get into a huge set of changes that 
break compilation and delay release again... granted, they can tag it at 
whatever commit they want but the idea is still the same... especially with the 
recent invasive change to requiring features only available in cmake greater 
than what is available in ubuntu 14.04.5... that's why the new 2.34 version of 
the dnc script can pull cmake from their repo and build it ;)

**Comment by onox** [comment]
#124 is also interesting. It could by implemented by collecting "damage" points (just a counter that you increase) if the RPM is higher than 2700. The more above 2700 RPM, the more points you collect. Once you reach a certain threshold, the engine can be considered "damaged". For example, if you fly at 2750 RPM, you get very little damage and it will take a long time to destroy the engine. 3000 RPM will increase the counter much faster and your engine will get destroyed much faster. Would the curve be exponential? What do you think?

**Comment by onox** [comment]
Is @jarlarntzen still working on the 3D model?

**Comment by gilbertohasnofb** [comment]
@onox The engine damage would be really interesting IMO! I like your idea of how to implement this. I think we could do as you say and have possibly an exponential curve, and then if the value is under a threshold value (something low) the engine is considered perfect, and then starting at the threshold the engine can start losing power or showing other problems (coughing for instance). We could add to the aircraft dialog an option to turn on engine damage. Then I think we could create a hotspot in the nose which would open the engine dialog, where you can see the status of the engine (possibly using some kind of progress bar such as these http://wiki.flightgear.org/Template:Progressbar ), the number of hours since the last overhaul and a button "overhaul the engine now". We can also add a counter in hours since last overhaul. What do you think? I would be glad to take care of the dialog, I love creating those :smile:

As for the damage, take a look at this:

> Engine Time – When looking at engines you want to look at their time since major overhaul (SMOH) or since factory remanufacture (SFRM). Up until 1968 Cessna equipped their 172’s with a Continental engine who’s TBO (time before overhaul) is 1800 hours versus the latter Lycoming engines who’s TBO is 2000 hours.
> 
> What does all of this mean? A TBO is the recommend complete engine overhaul time, a procedure that costs roughly 16,000-30,000 depending on your engine. Now that’s not to say an engine can’t over over TBO, I’ve flown some 172’s with 2600 hours on the engine! 

From: http://www.m0a.com/buying-a-cessna-172-part-3-of-5/

Maybe this link will be interesting as well: http://diversiorum.org/sape/pilotage/Engines/index.html

> Is @jarlarntzen still working on the 3D model?

Never heard back from him. 

@wkitty42 thanks for all the info. I know that you keep a close eye to the dev list, so if you hear anything concerning the release date could you please post it here?

@onox @dg-505  what about the tutorials? Do we plan to move them to whatever airport will be the new default at 2013.4? Currently our tutorials are not even set in Rio de Janeiro, but rather in Barcelone! Personally I think it's way too much hassle to change this, test it and make sure no bugs are present for every 3 months... so I wouldn't mind leaving it at Barcelona. But we must fix the issue #849 before the release!

**Comment by gilbertohasnofb** [comment]
I just read in the dev list a message by Torsten asking what still needs to be done before the release next week, so I suppose version 2016.4 will be shipped in the expected date indeed. In that case:

- @onox maybe it would be better to leave this work on the engine for after the release, as not to rush things and introduce unwanted effects, what do you think?
- @dg-505 can you let us know about the tutorial bug as soon as possible? I am really not familiar with how the tutorials work and I am lacking time to check it myself, but IMO that's something we must address as that tutorial is basically broken right now
- we should aim to have a release branch in the next days I suppose and then contact Stuart for a merge. I will drop him a message today just for a heads up

**Comment by onox** [comment]
> maybe it would be better to leave this work on the engine for after the release, as not to rush things and introduce unwanted effects, what do you think?

It would indeed be better to move it to the next milestone.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by onox** [comment]
I have moved most of the issues to the next milestones.

**Comment by wkitty42** [comment]
On 11/09/2016 03:49 PM, onox wrote:
>     maybe it would be better to leave this work on the engine for after the
>     release, as not to rush things and introduce unwanted effects, what do you
>     think?
>
> It would indeed be better to move it to the next milestone.

agreed... time is too short... i'm even wondering about some recent changes to 
the sim being completed enough to not cause problems with the new release... i 
won't even mention anything about determining EoL versions if the sim ;)

**Comment by wlbragg** [comment]
I really like @onox point system idea for engine damage and also @gilbertohasnofb hotspot idea at the engine cowling (wherever the engine access opening is).

>the engine can start losing power or showing other problems (coughing for instance)

Another indicator of damage to the engine is more "white" smoke.

**Comment by gilbertohasnofb** [comment]
@wlbragg the smoke idea is great! So we could work on this very soon, let's just get this release done and then we move on. (Stuart told me he can merge our release branch to FGDATA either on Saturday 2000 UTC or on Monday).

**Comment by onox** [comment]
Anything to add to #829 or can I create the release?

**Comment by onox** [comment]
I have released 2016.4. [`release/2016.4`](https://github.com/Juanvvc/c172p-detailed/tree/release/2016.4) branch has been created.

**Comment by gilbertohasnofb** [comment]
👍 I will write Stuart then!
