### ISSUE TITLE
Turn coordinator's moving ball texture

### ISSUE THREAD

**Issue by gilbertohasnofb** [Juanvvc/c172p-detailed#92]
The moving ball in the turn coordinator is slightly cut on each side (see picture below, note how both the left and right sides of the ball are totally straight, while the texture file is really round).

https://dl.dropboxusercontent.com/u/2730444/flightgear/devel/tc.png

**Comment by Juanvvc** [comment]
I tried to fix this and a new bug appeared.

It seems the algorithm flightgear uses to move textures aims to fast instead of accurate transformations. As a result, the ball is perfect when it is on the right side, but the antialising of the border desapears when the ball is on the left side. I'm not sure how to fix this.

**Comment by gilbertohasnofb** [comment]
Ok, so I exchanged the labels enhancement to bug, and let's leave this issue opened. Maybe in the future someone will find out how to solve this.

**Comment by gilbertohasnofb** [comment]
Hasn't this been fixed by @dany93 ?

**Comment by dany93** [comment]
I would say this is fixed (but I'm far from being a champion in Blender and Gimp).
This image http://forum.flightgear.org/viewtopic.php?f=4&t=25157&start=780#p237373

**Comment by gilbertohasnofb** [comment]
I tested it and it seems to be fixed. The size and colour are now much better and the problem mentioned by Juan before in which the texture gets aliased on one side of the TC but not on the other is not present any longer. I'd say we close this issue now.
